import { defineResilientAsyncComponent as defineAsyncComponent } from '@/logic/utils/resilientComponent';

export const SYSTEM_MODAL_REGISTRY = {
  Confirm: defineAsyncComponent(() => import('@/components/modals/ConfirmModal.vue')),
  Prompt: defineAsyncComponent(() => import('@/components/modals/PromptModal.vue')),
  PokemonCenter: defineAsyncComponent(() => import('@/components/modals/HealModal.vue')),
  HealOverlay: defineAsyncComponent(() => import('@/components/modals/HealModal.vue')),
  Inventory: defineAsyncComponent(() => import('@/components/modals/InventoryModal.vue')),
  Settings: defineAsyncComponent(() => import('@/components/modals/SettingsModal.vue')),
  Profile: defineAsyncComponent(() => import('@/components/modals/ProfileModal.vue')),
  Rename: defineAsyncComponent(() => import('@/components/modals/RenameModal.vue')),
  TrainerProfile: defineAsyncComponent(() => import('@/components/modals/TrainerProfileModal.vue')),
  Ranking: defineAsyncComponent(() => import('@/components/modals/RankingModal.vue')),
  Library: defineAsyncComponent(() => import('@/components/modals/LibraryModal.vue')),
  Cosmetics: defineAsyncComponent(() => import('@/components/modals/CosmeticsModal.vue')),
  ClassSelection: defineAsyncComponent(() => import('@/components/modals/ClassSelectionModal.vue')),
  ClassMissions: defineAsyncComponent(() => import('@/components/modals/ClassMissionsModal.vue')),
  PassiveTeamEditor: defineAsyncComponent(() => import('@/components/modals/PassiveTeamEditorModal.vue')),
  FactionChoice: defineAsyncComponent(() => import('@/components/modals/FactionChoiceModal.vue')),
  SocialCenter: defineAsyncComponent(() => import('@/components/social/SocialCenterModal.vue')),
  FactionWar: defineAsyncComponent(() => import('@/components/modals/FactionWarModal.vue')),
  SessionConflict: defineAsyncComponent(() => import('@/components/auth/SessionConflictModal.vue')),
  Fishing: defineAsyncComponent(() => import('@/components/modals/FishingModal.vue')),
  Archaeology: defineAsyncComponent(() => import('@/components/modals/ArchaeologyModal.vue')),
  EncounterSequence: defineAsyncComponent(() => import('@/components/game/EncounterSequence.vue')),
  DaycareMissions: defineAsyncComponent(() => import('@/components/modals/EventMissionsModal.vue')),
  EventMissions: defineAsyncComponent(() => import('@/components/modals/EventMissionsModal.vue')),
  EventDetail: defineAsyncComponent(() => import('@/components/modals/EventDetailModal.vue')),
  EventSlotAction: defineAsyncComponent(() => import('@/components/modals/EventSlotActionModal.vue')),
  EventAutoEnroll: defineAsyncComponent(() => import('@/components/modals/EventAutoEnrollModal.vue')),
  RouteSpawns: defineAsyncComponent(() => import('@/components/modals/RouteSpawnsModal.vue')),
  DebugStackTest: defineAsyncComponent(() => import('@/components/modals/DebugStackTestModal.vue')),
  DebugWeatherTables: defineAsyncComponent(() => import('@/components/modals/DebugWeatherTablesModal.vue')),
  Trade: defineAsyncComponent(() => import('@/components/market/TradeView.vue')),
};

export type SystemModalKey = keyof typeof SYSTEM_MODAL_REGISTRY;
