# Dockerfile - Poké Vicio Database
# Esta imagen contiene el motor de Supabase y el esquema del juego pre-instalado.

FROM supabase/postgres:15.1.0.147

# Copiamos los esquemas y las migraciones al directorio de inicialización estándar de Postgres
COPY ./database/schemas /docker-entrypoint-initdb.d/
COPY ./database/migrations /docker-entrypoint-initdb.d/

# El resto de la configuración se hereda de la imagen base de Supabase.
