/**
 * tests/node/inventory/item_id_normalization.test.ts
 *
 * Regression test for fuzzer item generator producing unnormalized item IDs like 'Air Balloon'
 * which fail getItemById() checks in the Vue UI layer.
 *
 * This test MUST FAIL before normalizing fuzzer_item_generator.ts and PASS after it.
 */

import { describe, it } from 'vitest';
import assert from 'node:assert/strict';
import { generateItemTestBatches } from '../../../scripts/e2e/fuzzer/generators/fuzzer_item_generator.ts';
import { getItemById, requireItemId } from '../../../src/data/inventory/items.ts';

describe('Fuzzer Item Generator — Strict Item ID Normalization', () => {
  it('generates item batches with strictly valid, normalized ItemIds readable by getItemById', () => {
    const batches = generateItemTestBatches(6);

    for (const batch of batches) {
      for (const item of batch.itemsToTest) {
        // Every item ID in itemsToTest MUST be resolved by requireItemId and exist in shop/items
        assert.doesNotThrow(() => {
          const resolved = requireItemId(item);
          getItemById(resolved);
        }, `Item ID "${item}" generated by fuzzer must be a valid, normalized ItemId in items database`);
      }

      for (const pokemon of batch.playerTeam) {
        if (pokemon.item) {
          assert.doesNotThrow(() => {
            const resolved = requireItemId(pokemon.item);
            getItemById(resolved);
          }, `Equipped item ID "${pokemon.item}" on player pokemon must be a valid, normalized ItemId`);
        }
      }
    }
  });
});
