/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/database/generate_migrations.ts
 * 
 * Lightweight metadata holding the current database migration version.
 * Decouples client version checks from the heavy migrations SQL data chunk.
 */

export const CLIENT_DB_VERSION = 20261008080000;
export const LATEST_MIGRATION_ID = '20261008080000_harden_supabase_postgres_best_practices';
