import { ref } from 'vue';

export const BATTLE_STATES = {
  CONTEXT_SETUP: 'CONTEXT_SETUP',
  INITIALIZING: 'INITIALIZING',
  FIRST_INTRO: 'FIRST_INTRO',
  SEARCH_PHASE: 'SEARCH_PHASE',
  ACTIVE_BATTLE: 'ACTIVE_BATTLE',
  REWARDS_PHASE: 'REWARDS_PHASE',
  LEVEL_UP_MODAL: 'LEVEL_UP_MODAL',
  POST_BATTLE_STABILIZATION: 'POST_BATTLE_STABILIZATION',
  REORDER_TEAM: 'REORDER_TEAM',
  EXIT_BATTLE: 'EXIT_BATTLE'
};

export const BATTLE_SUBSTATES = {
  WAIT_INPUT: 'WAIT_INPUT',
  EXEC_TURN: 'EXEC_TURN',
  CATCH_PROCESS: 'CATCH_PROCESS',
  CATCH_SHAKE: 'CATCH_SHAKE',
  CATCH_BREAK: 'CATCH_BREAK',
  CATCH_SUCCESS: 'CATCH_SUCCESS',
  ENEMY_FAINT: 'ENEMY_FAINT',
  PLAYER_FAINT_SEQ: 'PLAYER_FAINT_SEQ',
  ESCAPE_PROCESS: 'ESCAPE_PROCESS',
  VOID_STATE: 'VOID_STATE',
  DISTRIBUTE_XP: 'DISTRIBUTE_XP',
  ENTRY_ANIM: 'ENTRY_ANIM',
  SPRITE_FAINT: 'SPRITE_FAINT',
  WAIT_FAINT: 'WAIT_FAINT',
  WAIT_LOG_QUEUE: 'WAIT_LOG_QUEUE',
  BUSH_IDLE: 'BUSH_IDLE',
  ENCOUNTER_ANIM: 'ENCOUNTER_ANIM',
  RECEIVE_CONFIG: 'RECEIVE_CONFIG',
  VALIDATE_WEIGHTS: 'VALIDATE_WEIGHTS',
  INJECT_FILTERS: 'INJECT_FILTERS',
  READY_FOR_GEN: 'READY_FOR_GEN',
  CHECK_PERSISTENCE: 'CHECK_PERSISTENCE',
  CHECK_SLOTS: 'CHECK_SLOTS',
  POPULATE_BOTH: 'POPULATE_BOTH',
  PROMOTE_AND_REPOPULATE: 'PROMOTE_AND_REPOPULATE',
  PROMOTE: 'PROMOTE',
  GEN_NEW_S2: 'GEN_NEW_S2',
  PRELOAD_COORDS: 'PRELOAD_COORDS',
  SHOW_ALL_MISSING_COMBAT_HUDS: 'SHOW_ALL_MISSING_COMBAT_HUDS',
  TURN_ENGINE: 'TURN_ENGINE',
  ENEMY_REPLACEMENT_SEQ: 'ENEMY_REPLACEMENT_SEQ',
  BUILD_QUEUE: 'BUILD_QUEUE',
  POP_ACTION: 'POP_ACTION',
  APPLY_MOVE: 'APPLY_MOVE',
  FLEE_ATTEMPT: 'FLEE_ATTEMPT',
  EVAL_HP: 'EVAL_HP',
  RESOLVE_PLAYER_FAINT: 'RESOLVE_PLAYER_FAINT',
  RESOLVE_ENEMY_FAINT: 'RESOLVE_ENEMY_FAINT',
  EVAL_CONTINUE: 'EVAL_CONTINUE',
  ENEMY_DEFEAT: 'ENEMY_DEFEAT',
  HIDE_ENEMY_COMBAT_HUD: 'HIDE_ENEMY_COMBAT_HUD',
  ADD_TO_STORAGE: 'ADD_TO_STORAGE',
  HIDE_ENEMY_COMBAT_HUD_KO: 'HIDE_ENEMY_COMBAT_HUD_KO',
  PLAY_ENEMY_FAINT: 'PLAY_ENEMY_FAINT',
  HIDE_ENEMY_COMBAT_HUD_ESC: 'HIDE_ENEMY_COMBAT_HUD_ESC',
  PLAY_ESCAPE_ANIM: 'PLAY_ESCAPE_ANIM',
  CLEANUP_MEMORY: 'CLEANUP_MEMORY',
  CHECK_REMAINING: 'CHECK_REMAINING',
  STABILIZE_STAGE: 'STABILIZE_STAGE',
  AI_NEXT_PICK: 'AI_NEXT_PICK',
  SELECT_COUNTER: 'SELECT_COUNTER',
  SHOW_ENEMY_COMBAT_HUD: 'SHOW_ENEMY_COMBAT_HUD',
  CHECK_OUTCOME: 'CHECK_OUTCOME',
  WAIT_LOG_QUEUE_ONLY: 'WAIT_LOG_QUEUE_ONLY',
  CHECK_PENDING: 'CHECK_PENDING',
  SHOW_CHOICE: 'SHOW_CHOICE',
  PARALLEL_PREP: 'PARALLEL_PREP',
  UI_SYNC: 'UI_SYNC',
  GRASS_SYNC: 'GRASS_SYNC',
  TEAM_SYNC: 'TEAM_SYNC',
  HUD_SYNC: 'HUD_SYNC',
  CHECK_BINOCULARS: 'CHECK_BINOCULARS',
  MINIGAME_CHECK: 'MINIGAME_CHECK',
  VANISH_LOOP: 'VANISH_LOOP',
  RECALL_FLOW: 'RECALL_FLOW',
  ANIM_SYNC: 'ANIM_SYNC',
  CHECK_TEAM: 'CHECK_TEAM',
  HAS_HEALTHY: 'HAS_HEALTHY',
  SWITCH_MENU: 'SWITCH_MENU',
  POKEMON_CALL: 'POKEMON_CALL',
  SHOW_PLAYER_COMBAT_HUD: 'SHOW_PLAYER_COMBAT_HUD',
  ALL_FAINTED: 'ALL_FAINTED',
  DEFEAT_SCREEN: 'DEFEAT_SCREEN',
  REORDER_TEAM: 'REORDER_TEAM',
  CHECK_PLAYER_SEAT: 'CHECK_PLAYER_SEAT',
  CHECK_OCCUPANCY: 'CHECK_OCCUPANCY',
  SWITCHING: 'SWITCHING',
  HIDE_TARGET_COMBAT_HUD: 'HIDE_TARGET_COMBAT_HUD',
  READ_TARGET: 'READ_TARGET',
  POKEMON_RECALL: 'POKEMON_RECALL',
  SHOW_TARGET_COMBAT_HUD: 'SHOW_TARGET_COMBAT_HUD',
  RENDER_BALL: 'RENDER_BALL',
  ENERGY_RECALL: 'ENERGY_RECALL',
  ENERGY_RELEASE: 'ENERGY_RELEASE',
  POKEMON_APPEAR: 'POKEMON_APPEAR',
  ENCOUNTER_TYPE_CHECK: 'ENCOUNTER_TYPE_CHECK',
  WILD_ENTRY: 'WILD_ENTRY',
  TRAINER_ENTRY: 'TRAINER_ENTRY',
  T_BUSH_LAYER: 'T_BUSH_LAYER',
  T_SPRITE_LAYER: 'T_SPRITE_LAYER',
  T_SILHOUETTE: 'T_SILHOUETTE',
  T_FULL_COLOR: 'T_FULL_COLOR',
  BUSH_LAYER: 'BUSH_LAYER',
  AESTHETIC_CHECK: 'AESTHETIC_CHECK',
  BUSH_FLOW: 'BUSH_FLOW',
  SKIP_BUSHES: 'SKIP_BUSHES',
  BUSH_SETUP: 'BUSH_SETUP',
  INSTANT_BUSHES: 'INSTANT_BUSHES',
  GRADUAL_BUSHES: 'GRADUAL_BUSHES',
  SILHOUETTE_LAYER: 'SILHOUETTE_LAYER',
  SILHOUETTE_MODE: 'SILHOUETTE_MODE',
  SOLID_SILHOUETTE: 'SOLID_SILHOUETTE',
  FULL_COLOR: 'FULL_COLOR',
  WILD_ENCOUNTER: 'WILD_ENCOUNTER',
  TRAINER_ENCOUNTER: 'TRAINER_ENCOUNTER',
  TRAINER_RETREAT: 'TRAINER_RETREAT',
  CHECK_AESTHETIC: 'CHECK_AESTHETIC',
  GROUND_FLOW: 'GROUND_FLOW',
  FLYING_FLOW: 'FLYING_FLOW',
  G_BINOCULARS: 'G_BINOCULARS',
  SILHOUETTE_JUMP: 'SILHOUETTE_JUMP',
  FULL_COLOR_JUMP: 'FULL_COLOR_JUMP',
  BUSHES_BACK: 'BUSHES_BACK',
  JUMP_SHADOW: 'JUMP_SHADOW',
  BUSH_FADE: 'BUSH_FADE',
  REVEAL_COLORS: 'REVEAL_COLORS',
  BUSHES_BACK_COLOR: 'BUSHES_BACK_COLOR',
  JUMP_COLOR: 'JUMP_COLOR',
  BUSH_FADE_COLOR: 'BUSH_FADE_COLOR',
  F_BINOCULARS: 'F_BINOCULARS',
  SILHOUETTE_FLY: 'SILHOUETTE_FLY',
  FULL_COLOR_FLY: 'FULL_COLOR_FLY',
  JUMP_SHADOW_F: 'JUMP_SHADOW_F',
  REVEAL_COLORS_F: 'REVEAL_COLORS_F',
  ENTRY_CHECK: 'ENTRY_CHECK',
  DEFEAT_WAIT: 'DEFEAT_WAIT',
  EXECUTE_CLEANUP: 'EXECUTE_CLEANUP',
  CLEAR_UI: 'CLEAR_UI',
  TRIGGER_CLOSE: 'TRIGGER_CLOSE',
  RESET_FLAGS: 'RESET_FLAGS',
  // Subestados de animación visual (leídos por BattleArenaView.vue y composables)
  EMPTY_WAIT: 'EMPTY_WAIT',
  WAIT_LOG_QUEUE_ESC: 'WAIT_LOG_QUEUE_ESC',
  UPDATE_BUTTON: 'UPDATE_BUTTON',
  HIDE_PLAYER_COMBAT_HUD: 'HIDE_PLAYER_COMBAT_HUD',
  T_HIDDEN: 'T_HIDDEN',
  BUSH_VISIBLE: 'BUSH_VISIBLE',
  HIDDEN: 'HIDDEN',
  SILHOUETTE_READY: 'SILHOUETTE_READY',
  COLOR_READY: 'COLOR_READY',
  JUMP_COLOR_F: 'JUMP_COLOR_F',
  SPRITE_JUMP: 'SPRITE_JUMP',
  SPRITE_FAINT: 'SPRITE_FAINT',
  GEN_DATA: 'GEN_DATA',
  VACATE_ALL_SEATS: 'VACATE_ALL_SEATS',
  VACATE_ENEMY_SEAT: 'VACATE_ENEMY_SEAT',
  HIDE_ALL_COMBAT_HUDS: 'HIDE_ALL_COMBAT_HUDS',
};

export function createBattleStateMachine() {
  const currentState = ref(BATTLE_STATES.EXIT_BATTLE);
  const currentSubState = ref(null);
  let transitionTimeout = null;

  // Simple strict transitions check based on the Mermaid diagram.
  const validTransitions = {
    [BATTLE_STATES.CONTEXT_SETUP]: [BATTLE_STATES.INITIALIZING],
    [BATTLE_STATES.INITIALIZING]: [BATTLE_STATES.FIRST_INTRO, BATTLE_STATES.SEARCH_PHASE],
    [BATTLE_STATES.FIRST_INTRO]: [BATTLE_STATES.ACTIVE_BATTLE],
    [BATTLE_STATES.SEARCH_PHASE]: [BATTLE_STATES.ACTIVE_BATTLE, BATTLE_STATES.EXIT_BATTLE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.FIRST_INTRO, BATTLE_STATES.REWARDS_PHASE],
    [BATTLE_STATES.ACTIVE_BATTLE]: [BATTLE_STATES.REWARDS_PHASE, BATTLE_STATES.EXIT_BATTLE, BATTLE_STATES.POST_BATTLE_STABILIZATION, 'ENEMY_FAINT', 'PLAYER_FAINT_SEQ'], 
    [BATTLE_STATES.REWARDS_PHASE]: [BATTLE_STATES.POST_BATTLE_STABILIZATION, BATTLE_STATES.SEARCH_PHASE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.EXIT_BATTLE, BATTLE_SUBSTATES.VOID_STATE, BATTLE_SUBSTATES.DISTRIBUTE_XP],
    [BATTLE_STATES.POST_BATTLE_STABILIZATION]: [BATTLE_STATES.LEVEL_UP_MODAL, BATTLE_STATES.REORDER_TEAM, BATTLE_STATES.SEARCH_PHASE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.EXIT_BATTLE],
    [BATTLE_STATES.LEVEL_UP_MODAL]: [BATTLE_STATES.POST_BATTLE_STABILIZATION, BATTLE_STATES.SEARCH_PHASE, BATTLE_STATES.INITIALIZING],
    [BATTLE_STATES.REORDER_TEAM]: [BATTLE_STATES.POST_BATTLE_STABILIZATION, BATTLE_STATES.SEARCH_PHASE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.ACTIVE_BATTLE, BATTLE_STATES.EXIT_BATTLE],
    [BATTLE_SUBSTATES.ENEMY_FAINT]: [BATTLE_STATES.REWARDS_PHASE],
    [BATTLE_SUBSTATES.PLAYER_FAINT_SEQ]: [BATTLE_STATES.ACTIVE_BATTLE, BATTLE_STATES.EXIT_BATTLE],
    [BATTLE_SUBSTATES.ESCAPE_PROCESS]: [BATTLE_STATES.REWARDS_PHASE, BATTLE_STATES.EXIT_BATTLE],
    [BATTLE_STATES.EXIT_BATTLE]: [BATTLE_STATES.CONTEXT_SETUP, BATTLE_STATES.INITIALIZING]
  };

  /**
   * Translates to a specific state or substate.
   * If a delay is provided, returns a Promise that resolves when the transition happens.
   */
  const transition = (newState, newSubState = null, delayMs = 0) => {
    return new Promise((resolve) => {
      if (transitionTimeout) {
        clearTimeout(transitionTimeout);
        transitionTimeout = null;
      }

      const executeTransition = () => {
        // Validation check (can be expanded for strict enforcement)
        if (newState && Object.values(BATTLE_STATES).includes(newState)) {
          const isSameState = currentState.value === newState;
          if (!isSameState && validTransitions[currentState.value] && !validTransitions[currentState.value].includes(newState) && newState !== BATTLE_STATES.EXIT_BATTLE) {
            console.warn(`[FSM] Unexpected transition: ${currentState.value} -> ${newState}`);
          }
          currentState.value = newState;
        } else if (newState && Object.values(BATTLE_SUBSTATES).includes(newState)) {
          // Si recibimos un sub-estado como primer argumento, mantenemos el estado actual 
          // a menos que sea necesario forzar uno (pero GEN_NEW_S2 es background)
          newSubState = newState;
        }

        if (newSubState) {
          currentSubState.value = newSubState;
        } else if (newState && currentState.value !== BATTLE_STATES.ACTIVE_BATTLE) {
          currentSubState.value = null; // Solo limpiamos substate si estamos cambiando de fase principal
        }

        console.log(`[Battle FSM] Transitioned to ${currentState.value}${currentSubState.value ? ' (' + currentSubState.value + ')' : ''}`);
        resolve();
      };

      if (delayMs > 0) {
        transitionTimeout = setTimeout(executeTransition, delayMs);
      } else {
        executeTransition();
      }
    });
  };

  const isState = (state) => currentState.value === state;
  const isSubState = (subState) => currentSubState.value === subState;

  return {
    currentState,
    currentSubState,
    transition,
    isState,
    isSubState
  };
}
