import { ref } from 'vue';
import { gsap } from 'gsap';
import { logger } from '../utils/logger.ts';

export const BATTLE_STATES = {
  CONTEXT_SETUP: 'CONTEXT_SETUP',
  INITIALIZING: 'INITIALIZING',
  FIRST_INTRO: 'FIRST_INTRO',
  SEARCH_PHASE: 'SEARCH_PHASE',
  ACTIVE_BATTLE: 'ACTIVE_BATTLE',
  REWARDS_PHASE: 'REWARDS_PHASE',
  LEVEL_UP_MODAL: 'LEVEL_UP_MODAL',
  POST_BATTLE_STABILIZATION: 'POST_BATTLE_STABILIZATION',
  REORDER_TEAM: 'REORDER_TEAM',
  EXIT_BATTLE: 'EXIT_BATTLE'
} as const;

export type BattleStateName = typeof BATTLE_STATES[keyof typeof BATTLE_STATES];

export const BATTLE_SUBSTATES = {
  WAIT_INPUT: 'WAIT_INPUT',
  EXEC_TURN: 'EXEC_TURN',
  CATCH_PROCESS: 'CATCH_PROCESS',
  CATCH_SHAKE: 'CATCH_SHAKE',
  CATCH_BREAK: 'CATCH_BREAK',
  CATCH_SUCCESS: 'CATCH_SUCCESS',
  ENEMY_FAINT: 'ENEMY_FAINT',
  PLAYER_FAINT_SEQ: 'PLAYER_FAINT_SEQ',
  ESCAPE_PROCESS: 'ESCAPE_PROCESS',
  EMPTY_WAIT: 'EMPTY_WAIT',
  ANIM_SYNC: 'ANIM_SYNC',
  DISTRIBUTE_XP: 'DISTRIBUTE_XP',
  ENTRY_ANIM: 'ENTRY_ANIM',
  WAIT_LOG_QUEUE: 'WAIT_LOG_QUEUE',
  BUSH_IDLE: 'BUSH_IDLE',
  ENCOUNTER_ANIM: 'ENCOUNTER_ANIM',
  RECEIVE_CONFIG: 'RECEIVE_CONFIG',
  GEN_NEW_S2: 'GEN_NEW_S2',
  CHECK_PERSISTENCE: 'CHECK_PERSISTENCE',
  PRELOAD_COORDS: 'PRELOAD_COORDS',
  PRELOAD_FINAL_COORDS: 'PRELOAD_FINAL_COORDS',
  TURN_ENGINE: 'TURN_ENGINE',
  ENEMY_REPLACEMENT_SEQ: 'ENEMY_REPLACEMENT_SEQ',
  BUILD_QUEUE: 'BUILD_QUEUE',
  POP_ACTION: 'POP_ACTION',
  APPLY_MOVE: 'APPLY_MOVE',
  FLEE_ATTEMPT: 'FLEE_ATTEMPT',
  EVAL_HP: 'EVAL_HP',
  RESOLVE_PLAYER_FAINT: 'RESOLVE_PLAYER_FAINT',
  RESOLVE_ENEMY_FAINT: 'RESOLVE_ENEMY_FAINT',
  EVAL_CONTINUE: 'EVAL_CONTINUE',
  ENEMY_DEFEAT: 'ENEMY_DEFEAT',
  ADD_TO_STORAGE: 'ADD_TO_STORAGE',
  PLAY_ENEMY_FAINT: 'PLAY_ENEMY_FAINT',
  PLAY_ESCAPE_ANIM: 'PLAY_ESCAPE_ANIM',
  CLEANUP_MEMORY: 'CLEANUP_MEMORY',
  CHECK_REMAINING: 'CHECK_REMAINING',
  STABILIZE_STAGE: 'STABILIZE_STAGE',
  AI_NEXT_PICK: 'AI_NEXT_PICK',
  SELECT_COUNTER: 'SELECT_COUNTER',
  CHECK_OUTCOME: 'CHECK_OUTCOME',
  WAIT_LOG_QUEUE_ONLY: 'WAIT_LOG_QUEUE_ONLY',
  CHECK_PENDING: 'CHECK_PENDING',
  SHOW_CHOICE: 'SHOW_CHOICE',
  PARALLEL_PREP: 'PARALLEL_PREP',
  MINIGAME_CHECK: 'MINIGAME_CHECK',
  RECALL_FLOW: 'RECALL_FLOW',
  CHECK_TEAM: 'CHECK_TEAM',
  HAS_HEALTHY: 'HAS_HEALTHY',
  SWITCH_MENU: 'SWITCH_MENU',
  POKEMON_CALL: 'POKEMON_CALL',
  ALL_FAINTED: 'ALL_FAINTED',
  DEFEAT_SCREEN: 'DEFEAT_SCREEN',
  SWITCHING: 'SWITCHING',
  POKEMON_RECALL: 'POKEMON_RECALL',
  RENDER_BALL: 'RENDER_BALL',
  ENERGY_RECALL: 'ENERGY_RECALL',
  ENERGY_RELEASE: 'ENERGY_RELEASE',
  POKEMON_APPEAR: 'POKEMON_APPEAR',
  VACATE_SEAT: 'VACATE_SEAT',
  FADEOUT_BALL: 'FADEOUT_BALL',
  OCCUPY_SEAT: 'OCCUPY_SEAT',
  ENCOUNTER_TYPE_CHECK: 'ENCOUNTER_TYPE_CHECK',
  WILD_ENTRY: 'WILD_ENTRY',
  TRAINER_ENTRY: 'TRAINER_ENTRY',
  PARALLEL_ENTRY: 'PARALLEL_ENTRY',
  T_VISUAL: 'T_VISUAL',
  WILD_ENCOUNTER: 'WILD_ENCOUNTER',
  TRAINER_ENCOUNTER: 'TRAINER_ENCOUNTER',
  TRAINER_RETREAT: 'TRAINER_RETREAT',
  CHECK_BINOCULARS: 'CHECK_BINOCULARS',
  PARALLEL_JUMP: 'PARALLEL_JUMP',
  JUMP_SHADOW: 'JUMP_SHADOW',
  JUMP_COLOR: 'JUMP_COLOR',
  BUSH_FADE: 'BUSH_FADE',
  REVEAL_COLORS: 'REVEAL_COLORS',
  ENTRY_CHECK: 'ENTRY_CHECK',
  DEFEAT_WAIT: 'DEFEAT_WAIT',
  EXECUTE_CLEANUP: 'EXECUTE_CLEANUP',
  CLEAR_UI: 'CLEAR_UI',
  TRIGGER_CLOSE: 'TRIGGER_CLOSE',
  RESET_FLAGS: 'RESET_FLAGS',
  UPDATE_BUTTON: 'UPDATE_BUTTON',
  BUSH_VISIBLE: 'BUSH_VISIBLE',
  SILHOUETTE_MODE: 'SILHOUETTE_MODE',
  INJECT_FILTERS: 'INJECT_FILTERS',
  READY_FOR_GEN: 'READY_FOR_GEN',
  VACATE_ALL_SEATS: 'VACATE_ALL_SEATS',
  APPLY_ITEM_MODIFIERS: 'APPLY_ITEM_MODIFIERS',
  WEIGHT_CALCULATION: 'WEIGHT_CALCULATION',
  ASYNC_THREAD: 'ASYNC_THREAD',
  CHECK_CONTEXT: 'CHECK_CONTEXT',
  GEN_TEAMS: 'GEN_TEAMS',
  MARK_EVENT: 'MARK_EVENT',
  SET_SEARCH_FLAG: 'SET_SEARCH_FLAG',
  FIND_HEALTHY: 'FIND_HEALTHY',
  CHECK_ACTIVE_SEAT: 'CHECK_ACTIVE_SEAT',
  WAIT_TIMER: 'WAIT_TIMER',
  SHOW_DIALOGS: 'SHOW_DIALOGS',
  CHECK_SLOTS: 'CHECK_SLOTS',
  PROMOTE_AND_REPOPULATE: 'PROMOTE_AND_REPOPULATE',
  PROMOTE: 'PROMOTE',
  AUTO_BATTLE_CHECK: 'AUTO_BATTLE_CHECK',
  RESET_STALE_VARIABLES: 'RESET_STALE_VARIABLES',
  PLAY_MINIGAME: 'PLAY_MINIGAME',
  MINIGAME_MODAL: 'MINIGAME_MODAL',
  MINIGAME_RESULT: 'MINIGAME_RESULT'
} as const;

export type BattleSubStateName = typeof BATTLE_SUBSTATES[keyof typeof BATTLE_SUBSTATES];

export function createBattleStateMachine() {
  const currentState = ref<BattleStateName>(BATTLE_STATES.EXIT_BATTLE);
  const currentSubState = ref<BattleSubStateName | null>(null);
  let transitionCall: gsap.core.Animation | null = null;

  // Simple strict transitions check based on the Mermaid diagram.
  const validTransitions: Record<string, string[]> = {
    [BATTLE_STATES.CONTEXT_SETUP]: [BATTLE_STATES.INITIALIZING],
    [BATTLE_STATES.INITIALIZING]: [BATTLE_STATES.FIRST_INTRO, BATTLE_STATES.SEARCH_PHASE],
    [BATTLE_STATES.FIRST_INTRO]: [BATTLE_STATES.ACTIVE_BATTLE, BATTLE_STATES.REORDER_TEAM],
    [BATTLE_STATES.SEARCH_PHASE]: [BATTLE_STATES.ACTIVE_BATTLE, BATTLE_STATES.EXIT_BATTLE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.FIRST_INTRO, BATTLE_STATES.REWARDS_PHASE],
    [BATTLE_STATES.ACTIVE_BATTLE]: [BATTLE_STATES.REWARDS_PHASE, BATTLE_STATES.EXIT_BATTLE, BATTLE_STATES.REORDER_TEAM, BATTLE_SUBSTATES.RESOLVE_ENEMY_FAINT, BATTLE_SUBSTATES.RESOLVE_PLAYER_FAINT, BATTLE_STATES.LEVEL_UP_MODAL], 
    [BATTLE_STATES.REWARDS_PHASE]: [BATTLE_STATES.REORDER_TEAM, BATTLE_STATES.SEARCH_PHASE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.EXIT_BATTLE, BATTLE_SUBSTATES.EMPTY_WAIT, BATTLE_SUBSTATES.DISTRIBUTE_XP, BATTLE_STATES.LEVEL_UP_MODAL],
    [BATTLE_STATES.LEVEL_UP_MODAL]: [BATTLE_STATES.REWARDS_PHASE, BATTLE_STATES.SEARCH_PHASE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.ACTIVE_BATTLE],
    [BATTLE_STATES.REORDER_TEAM]: [BATTLE_STATES.SEARCH_PHASE, BATTLE_STATES.INITIALIZING, BATTLE_STATES.ACTIVE_BATTLE, BATTLE_STATES.EXIT_BATTLE],
    [BATTLE_SUBSTATES.RESOLVE_ENEMY_FAINT]: [BATTLE_SUBSTATES.ENEMY_DEFEAT],
    [BATTLE_SUBSTATES.RESOLVE_PLAYER_FAINT]: [BATTLE_SUBSTATES.PLAYER_FAINT_SEQ],
    [BATTLE_SUBSTATES.ENEMY_DEFEAT]: [BATTLE_STATES.REWARDS_PHASE],
    [BATTLE_SUBSTATES.PLAYER_FAINT_SEQ]: [BATTLE_STATES.ACTIVE_BATTLE, BATTLE_STATES.EXIT_BATTLE],
    [BATTLE_SUBSTATES.ESCAPE_PROCESS]: [BATTLE_STATES.REWARDS_PHASE, BATTLE_STATES.EXIT_BATTLE],
    [BATTLE_STATES.EXIT_BATTLE]: [BATTLE_STATES.CONTEXT_SETUP, BATTLE_STATES.INITIALIZING]
  };

  /**
   * Translates to a specific state or substate.
   * If a delay is provided, returns a Promise that resolves when the transition happens.
   */
  const transition = (newState: BattleStateName | BattleSubStateName, newSubState: BattleSubStateName | null = null, delayMs: number = 0): Promise<void> => {
    return new Promise<void>((resolve) => {
      if (transitionCall) {
        transitionCall.kill();
        transitionCall = null;
      }

      const executeTransition = () => {
        // Validation check (can be expanded for strict enforcement)
        if (newState && (Object.values(BATTLE_STATES) as readonly string[]).includes(newState)) {
          const isSameState = currentState.value === newState;
          const allowedTransitions = validTransitions[currentState.value];
          if (!isSameState && allowedTransitions && !allowedTransitions.includes(newState) && newState !== BATTLE_STATES.EXIT_BATTLE) {
            logger.warn('FSM', `Unexpected transition: ${currentState.value} -> ${newState}`);
          }
          currentState.value = newState as BattleStateName;
        } else if (newState && (Object.values(BATTLE_SUBSTATES) as readonly string[]).includes(newState)) {
          // Si recibimos un sub-estado como primer argumento, mantenemos el estado actual 
          newSubState = newState as BattleSubStateName;
        }

        if (newSubState) {
          currentSubState.value = newSubState;
        } else if (newState && currentState.value !== BATTLE_STATES.ACTIVE_BATTLE) {
          currentSubState.value = null; // Solo limpiamos substate si estamos cambiando de fase principal
        }

        logger.debug('Battle FSM', `Transitioned to ${currentState.value}${currentSubState.value ? ' (' + currentSubState.value + ')' : ''}`);
        resolve(undefined);
      };

      if (delayMs > 0) {
        transitionCall = gsap.delayedCall(delayMs / 1000, executeTransition);
      } else {
        executeTransition();
      }
    });
  };

  const isState = (state: string) => currentState.value === state;
  const isSubState = (subState: string | null) => currentSubState.value === subState;

  return {
    currentState,
    currentSubState,
    transition,
    isState,
    isSubState
  };
}
