// fallow-ignore-file circular-dependencies
import { defineAsyncComponent } from 'vue'


/**
 * Modal Registry
 * Maps modal names to their lazy-loaded components.
 */
export const MODAL_REGISTRY = {
  Confirm: defineAsyncComponent(() => import('@/components/modals/ConfirmModal.vue')),
  Prompt: defineAsyncComponent(() => import('@/components/modals/PromptModal.vue')),
  Shop: defineAsyncComponent(() => import('@/components/modals/ShopModal.vue')),
  GlobalMarket: defineAsyncComponent(() => import('@/components/modals/GlobalMarketModal.vue')),
  BCShop: defineAsyncComponent(() => import('@/components/modals/BCShopModal.vue')),
  PokemonCenter: defineAsyncComponent(() => import('@/components/modals/HealModal.vue')),
  Inventory: defineAsyncComponent(() => import('@/components/modals/InventoryModal.vue')),
  PokemonDetail: defineAsyncComponent(() => import('@/components/modals/UnifiedPokemonDetailModal.vue')),
  MoveDetail: defineAsyncComponent(() => import('@/components/MoveDetailModal.vue')),
  Evolution: defineAsyncComponent(() => import('@/components/evolution/EvolutionScene.vue')),
  Settings: defineAsyncComponent(() => import('@/components/SettingsModal.vue')),
  Profile: defineAsyncComponent(() => import('@/components/ProfileModal.vue')),
  Rename: defineAsyncComponent(() => import('@/components/modals/RenameModal.vue')),
  TrainerProfile: defineAsyncComponent(() => import('@/components/modals/TrainerProfileModal.vue')),
  Ranking: defineAsyncComponent(() => import('@/components/modals/RankingModal.vue')),
  Arena: defineAsyncComponent(() => import('@/components/modals/ArenaModal.vue')),
  Library: defineAsyncComponent(() => import('@/components/LibraryModal.vue')),
  Cosmetics: defineAsyncComponent(() => import('@/components/modals/CosmeticsModal.vue')),
  ClassSelection: defineAsyncComponent(() => import('@/components/modals/ClassSelectionModal.vue')),
  ClassMissions: defineAsyncComponent(() => import('@/components/modals/ClassMissionsModal.vue')),
  MoveLearning: defineAsyncComponent(() => import('@/components/modals/MoveLearningModal.vue')),
  MoveRelearner: defineAsyncComponent(() => import('@/components/modals/MoveRelearnerModal.vue')),
  PokemonSelection: defineAsyncComponent(() => import('@/components/modals/PokemonSelectionModal.vue')),
  WarShop: defineAsyncComponent(() => import('@/components/modals/war-shop/WarShopModal.vue')),
  PassiveTeamEditor: defineAsyncComponent(() => import('@/components/PassiveTeamEditorModal.vue')),
  FactionChoice: defineAsyncComponent(() => import('@/components/FactionChoiceModal.vue')),
  SocialCenter: defineAsyncComponent(() => import('@/components/social/SocialCenterModal.vue')),
  PokedexDetail: defineAsyncComponent(() => import('@/components/modals/UnifiedPokemonDetailModal.vue')),
  HatchAnimation: defineAsyncComponent(() => import('@/components/breeding/HatchAnimationModal.vue')),
  Daycare: defineAsyncComponent(() => import('@/components/modals/DaycareModal.vue')),
  DaycareMissions: defineAsyncComponent(() => import('@/components/modals/EventMissionsModal.vue')),
  EventMissions: defineAsyncComponent(() => import('@/components/modals/EventMissionsModal.vue')),
  WorldEvents: defineAsyncComponent(() => import('@/components/modals/WorldEventsModal.vue')),
  FactionWar: defineAsyncComponent(() => import('@/components/modals/FactionWarModal.vue')),
  BattleSwitch: defineAsyncComponent(() => import('@/components/modals/PokemonSelectionModal.vue')),
  SessionConflict: defineAsyncComponent(() => import('@/components/auth/SessionConflictModal.vue')),
  Trade: defineAsyncComponent(() => import('@/components/TradeView.vue')),
  HealOverlay: defineAsyncComponent(() => import('@/components/modals/HealModal.vue')),
  NaturePatch: defineAsyncComponent(() => import('@/components/modals/NaturePatchModal.vue')),
  PPUp: defineAsyncComponent(() => import('@/components/modals/PPUpModal.vue')),
  AbilityPill: defineAsyncComponent(() => import('@/components/modals/AbilityPillModal.vue')),
  StonePicker: defineAsyncComponent(() => import('@/components/modals/StonePickerModal.vue')),
  Fishing: defineAsyncComponent(() => import('@/components/modals/FishingModal.vue')),
  Archaeology: defineAsyncComponent(() => import('@/components/modals/ArchaeologyModal.vue')),
  EncounterSequence: defineAsyncComponent(() => import('@/components/game/EncounterSequence.vue')),
  EventDetail: defineAsyncComponent(() => import('@/components/modals/EventDetailModal.vue')),
  TeamManagement: defineAsyncComponent(() => import('@/components/modals/TeamManagementModal.vue')),
  BoxPokemonMenu: defineAsyncComponent(() => import('@/components/box/BoxPokemonMenu.vue')),
  BoxMove: defineAsyncComponent(() => import('@/components/box/BoxMoveModal.vue')),
  DebugStackTest: defineAsyncComponent(() => import('@/components/modals/DebugStackTestModal.vue')),
  DebugWeatherTables: defineAsyncComponent(() => import('@/components/modals/DebugWeatherTablesModal.vue')),
  RouteSpawns: defineAsyncComponent(() => import('@/components/modals/RouteSpawnsModal.vue'))
}
