// fallow-ignore-file security-sink
/**
 * @file configure_official_servers.ts
 * @description Script automático para parsear el archivo .env maestro y configurar src/data/official_servers.ts.
 * 
 * UTILIDAD:
 * Extrae las configuraciones de cada perfil de servidor (SERVER_<profile>_*) y genera
 * la lista OFFICIAL_SERVERS para la interfaz de usuario del juego. Pisa completamente
 * la configuración anterior con los datos exactos del .env maestro.
 * 
 * CUMPLE CON:
 * - Regla de Aislamiento y Parseo Multi-Servidor (env-multi-server-parser).
 * - Estándares Node.js 26+ (Explicit Resource Management con 'using', prefijos node:).
 */

import fsPromises from 'node:fs/promises';
import path from 'node:path';
import { styleText } from 'node:util';
import { enableCompileCache } from 'node:module';

// Optimizar ejecución en ejecuciones sucesivas
enableCompileCache();

const ENV_FILE = path.resolve(process.cwd(), '.env');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/data/system/official_servers.ts');

export async function configureOfficialServers(): Promise<void> {
  console.log(styleText('bold', '\n--- 🌐 OFFICIAL SERVERS CONFIGURATOR (Node.js 26+) ---'));
  console.log(styleText('cyan', `📄 Leyendo archivo .env maestro: ${ENV_FILE}`));

  try {
    await fsPromises.access(ENV_FILE);
  } catch {
    console.error(styleText('red', '❌ Error: Archivo .env maestro no encontrado.'));
    process.exit(1);
  }



  const { readAndParseEnv } = await import('../lib/supabaseClient.ts');
  const serverConfigs = await readAndParseEnv();

  const profiles = Object.keys(serverConfigs);
  if (profiles.length === 0) {
    console.warn(styleText('yellow', '⚠️ Advertencia: No se encontraron configuraciones de servidor (SERVER_<profile>_*) en el .env.'));
  } else {
    console.log(styleText('green', `✅ Se encontraron ${profiles.length} perfiles de servidor: ${profiles.join(', ')}`));
  }

  // Verificar si algún perfil tiene explícitamente IS_DEFAULT=true
  const hasExplicitDefault = profiles.some(p => (serverConfigs[p] || {}).IS_DEFAULT === 'true');

  const officialServers = profiles.map((profile) => {
    const conf = serverConfigs[profile] || {};
    const id = conf.ID || profile;
    const name = conf.NAME || profile;
    const region = conf.REGION || 'Desarrollo';
    
    // Determinar URLs y Claves exactas del .env (pisando todo lo viejo)
    const url = conf.SUPABASE_PUBLIC_URL || conf.SUPABASE_URL || conf.SITE_URL || conf.API_EXTERNAL_URL || conf.URL || '';
    const anonKey = conf.ANON_KEY || conf.SUPABASE_ANON_KEY || conf.KEY || '';

    let isDefaultVal = false;
    if (hasExplicitDefault) {
      isDefaultVal = conf.IS_DEFAULT === 'true';
    } else {
      isDefaultVal = profile === 'cloud' || id === 'official_prod';
    }

    let serverObjStr = `  {\n    id: '${id}',\n    name: '${name}',\n    region: '${region}',\n    url: '${url}',\n    anonKey: '${anonKey}'`;
    if (isDefaultVal) {
      serverObjStr += `,\n    isDefault: true`;
    }
    serverObjStr += `\n  }`;
    return serverObjStr;
  });

  const outputContent = `/**
 * AUTO-GENERATED OFFICIAL SERVERS CONFIGURATION
 * Generated by scripts/configure_official_servers.ts
 * Last configured: ${Temporal.Now.instant().toString()}
 * 
 * Lista de servidores registrados para la GUI de Login.
 * Creado automáticamente a partir del archivo .env maestro.
 */

export interface OfficialServer {
  id: string;
  name: string;
  region: string;
  url: string;
  anonKey: string;
  isDefault?: boolean;
}

export const OFFICIAL_SERVERS: OfficialServer[] = [
${officialServers.join(',\n')}
];

export const DEFAULT_SERVER = (OFFICIAL_SERVERS.find(s => s.isDefault) || OFFICIAL_SERVERS[0]) as OfficialServer;
`;

  // Asegurar que el directorio de salida exista
  const outputDir = path.dirname(OUTPUT_FILE);
  await fsPromises.mkdir(outputDir, { recursive: true });

  await fsPromises.writeFile(OUTPUT_FILE, outputContent, 'utf-8');
  console.log(styleText('green', `✨ src/data/official_servers.ts configurado exitosamente con ${profiles.length} servidores.\n`));
}

// Permitir ejecución directa
const isDirectRun = process.argv[1] && (
  process.argv[1].endsWith('configure_official_servers.ts') ||
  process.argv[1].includes('configure_official_servers.ts')
);

if (isDirectRun) {
  configureOfficialServers().catch((err) => {
    console.error(styleText('red', `❌ Error fatal: ${(err as Error).message}`));
    process.exit(1);
  });
}
