-- =====================================================
-- POKÉ VICIO — MIGRACIÓN DE INVENTARIO A IDS (v3)
-- Fecha: 2026-06-11
-- Descripción: Convierte claves de inventario en español a IDs y establece db_version = 3.
-- =====================================================

DO $$
DECLARE
  r RECORD;
  v_inventory JSONB;
  v_new_inventory JSONB;
  v_item_key TEXT;
  v_item_qty INTEGER;
  v_mapped_id TEXT;
  v_mapping JSONB;
  v_valid_ids JSONB;
BEGIN
  -- Definición del mapa de traducción Oficial (Español -> ID)
  v_mapping := '{
    "PociÃ³n": "potion",
    "PokÃ©ball": "pokeball",
    "Super Poción": "super_potion",
    "Carbón": "charcoal",
    "Baya de Bronce": "berry_bronze",
    "Baya de Plata": "berry_silver",
    "Baya de Oro": "berry_gold",
    "Agua Mística": "mystic_water",
    "Piedra Eterna": "everstone",
    "Lazo Destino": "destiny_knot",
    "Restaurador de Vigor": "vigor_restorer",
    "Pesa Recia": "power_weight",
    "Brazal Recio": "power_bracer",
    "Cinto Recio": "power_belt",
    "Lente Recia": "power_lens",
    "Banda Recia": "power_band",
    "Franja Recia": "power_anklet",
    "Pokéball": "pokeball",
    "Súper Ball": "great_ball",
    "Ultra Ball": "ultra_ball",
    "Red Ball": "net_ball",
    "Ocaso Ball": "dusk_ball",
    "Turno Ball": "timer_ball",
    "Master Ball": "master_ball",
    "Poción": "potion",
    "Súper Poción": "super_potion",
    "Hiper Poción": "hyper_potion",
    "Poción Máxima": "max_potion",
    "Refresco": "soda_pop",
    "Limonada": "lemonade",
    "Revivir": "revive",
    "Revivir Máximo": "revive_max",
    "Antídoto": "antidoto",
    "Cura Quemadura": "burn_heal",
    "Despertar": "awakening",
    "Cura Total": "full_heal",
    "Éter": "ether",
    "Elixir": "elixir",
    "Elixir Máximo": "elixir_max",
    "Piedra Fuego": "fire_stone",
    "Piedra Agua": "water_stone",
    "Piedra Trueno": "thunder_stone",
    "Piedra Hoja": "leaf_stone",
    "Piedra Lunar": "moon_stone",
    "Piedra Solar": "sun_stone",
    "Compartir EXP": "exp_share",
    "Restos": "leftovers",
    "Cascabel Concha": "shell_bell",
    "Cinta Elegida": "choice_band",
    "Banda Focus": "focus_sash",
    "Lente Zoom": "scope_lens",
    "Imán": "magnet",
    "Caramelo Raro": "rare_candy",
    "Caramelo de vigor": "vigor_candy",
    "Recordador de Movimientos": "move_relearner",
    "Parche de naturaleza": "nature_patch",
    "Píldora de cambio de habilidad": "ability_pill",
    "Ticket Shiny": "ticket_shiny",
    "Moneda Amuleto": "amulet_coin",
    "Ticket Safari": "ticket_safari",
    "Ticket Cueva Celeste": "ticket_cerulean",
    "Incienso Fuego": "incense_fire",
    "Incienso Agua": "incense_water",
    "Incienso Planta": "incense_grass",
    "Incienso Normal": "incense_normal",
    "Incienso Fantasma": "incense_ghost",
    "Incienso Psíquico": "incense_psychic",
    "Subida de PP": "pp_up",
    "Subida PP": "pp_up",
    "Huevo Suerte Pequeño": "lucky_egg",
    "Repelente": "repel",
    "Superrepelente": "super_repel",
    "Máximo Repelente": "max_repel",
    "Caña de pescar": "fishing_rod",
    "Caña Buena": "fishing_rod_good",
    "Supercaña": "fishing_rod_super",
    "Pico de excavación": "pickaxe",
    "Pico Bueno": "pickaxe_silver",
    "Superpico": "pickaxe_gold",
    "Pincel de excavación": "brush",
    "Pincel Bueno": "brush_good",
    "Superpincel": "brush_super",
    "Fósil Hélix": "helix_fossil",
    "Fósil Domo": "dome_fossil",
    "Ámbar Viejo": "old_amber",
    "Pepita": "nugget",
    "Perla": "pearl",
    "Perla Grande": "big_pearl",
    "Polvo Estelar": "stardust",
    "Trozo Estrella": "star_piece",
    "Mineral de Carbón": "coal_ore",
    "Mineral de Cobre": "copper_ore",
    "Mineral de Hierro": "iron_ore",
    "Mineral de Plata": "silver_ore",
    "Mineral de Oro": "gold_ore",
    "Mineral de Wolframio": "tungsten_ore",
    "Mineral de Uranio": "uranium_ore",
    "Mineral de Rubí": "rubi_ore",
    "Mineral de Zafiro": "zaphire_ore",
    "Mineral de Esmeralda": "emmerald_ore",
    "Mineral de Topacio": "topaz_ore",
    "Mineral de Diamante": "diamond_ore",
    "Lingote de Cobre": "copper",
    "Lingote de Hierro": "iron",
    "Lingote de Plata": "silver",
    "Lingote de Oro": "gold",
    "Lingote de Wolframio": "tungsten",
    "Lingote de Uranio": "uranium",
    "Rubí Pulido": "rubi",
    "Zafiro Pulido": "zaphire",
    "Esmeralda Pulida": "emmerald",
    "Topacio Pulido": "topaz",
    "Diamante Pulido": "diamond",
    "Bola Luminosa": "light_ball",
    "Hueso Grueso": "thick_club",
    "Palo": "stick",
    "Polvo Metálico": "metal_powder",
    "Cuchara Torcida": "twisted_spoon",
    "Hechizo": "spell_tag",
    "Ticket Articuno": "ticket_articuno",
    "Ticket Mewtwo": "ticket_mewtwo",
    "Escáner de IVs": "iv_scanner",
    "MT01 Puño Certero": "tm01",
    "MT02 Garra Dragón": "tm02",
    "MT03 Pulso Agua": "tm03",
    "MT04 Paz Mental": "tm04",
    "MT05 Rugido": "tm05",
    "MT06 Tóxico": "tm06",
    "MT Tóxico": "tm06",
    "MT07 Granizo": "tm07",
    "MT08 Corpulencia": "tm08",
    "MT09 Recurrente": "tm09",
    "MT10 Poder Oculto": "tm10",
    "MT11 Día Soleado": "tm11",
    "MT12 Mofa": "tm12",
    "MT13 Rayo Hielo": "tm13",
    "MT14 Ventisca": "tm14",
    "MT15 Hiperrayo": "tm15",
    "MT16 Pantalla de Luz": "tm16",
    "MT17 Protección": "tm17",
    "MT18 Danza Lluvia": "tm18",
    "MT19 Gigadrenado": "tm19",
    "MT20 Velo Sagrado": "tm20",
    "MT21 Frustración": "tm21",
    "MT22 Rayo Solar": "tm22",
    "MT23 Cola Férrea": "tm23",
    "MT24 Rayo": "tm24",
    "MT25 Trueno": "tm25",
    "MT26 Terremoto": "tm26",
    "MT27 Retribución": "tm27",
    "MT28 Excavar": "tm28",
    "MT29 Psíquico": "tm29",
    "MT30 Bola Sombra": "tm30",
    "MT31 Demolición": "tm31",
    "MT32 Doble Equipo": "tm32",
    "MT33 Reflejo": "tm33",
    "MT34 Onda Voltio": "tm34",
    "MT35 Lanzallamas": "tm35",
    "MT36 Bomba Lodo": "tm36",
    "MT37 Tormenta de Arena": "tm37",
    "MT38 Llamarada": "tm38",
    "MT39 Tumba Rocas": "tm39",
    "MT40 Golpe Aéreo": "tm40",
    "MT41 Tormento": "tm41",
    "MT42 Imagen": "tm42",
    "MT43 Daño Secreto": "tm43",
    "MT44 Descanso": "tm44",
    "MT45 Atracción": "tm45",
    "MT46 Ladrón": "tm46",
    "MT47 Ala de Acero": "tm47",
    "MT48 Intercambio": "tm48",
    "MT49 Robo": "tm49",
    "MT50 Sofoco": "tm50",
    "acid": "acid",
    "apricorn_blue": "apricorn_blue",
    "apricorn_red": "apricorn_red",
    "apricorn_yellow": "apricorn_yellow",
    "berry_sugar": "berry_sugar",
    "bone_fragment": "bone_fragment",
    "broccoli": "broccoli",
    "carrot": "carrot",
    "cloth": "cloth",
    "combee_honey": "combee_honey",
    "dawn_stone": "dawn_stone",
    "dusk_stone": "dusk_stone",
    "electronic_scrap": "electronic_scrap",
    "energy_powder": "energy_powder",
    "food_scraps": "food_scraps",
    "fresh_water": "fresh_water",
    "herb_rare": "herb_rare",
    "ice_crystal": "ice_crystal",
    "ice_stone": "ice_stone",
    "leather_strip": "leather_strip",
    "lettuce": "lettuce",
    "liechi_berry": "liechi_berry",
    "metal_scrap": "metal_scrap",
    "mushroom": "mushroom",
    "nickel_ore": "nickel_ore",
    "oil": "oil",
    "onion": "onion",
    "pecha_berry_wild": "pecha_berry_wild",
    "petrified_sap": "petrified_sap",
    "pigment_black": "pigment_black",
    "pigment_blue": "pigment_blue",
    "pigment_green": "pigment_green",
    "pigment_orange": "pigment_orange",
    "pigment_purple": "pigment_purple",
    "pigment_red": "pigment_red",
    "pigment_white": "pigment_white",
    "pigment_yellow": "pigment_yellow",
    "potato": "potato",
    "revive_root": "revive_root",
    "rubber_compound": "rubber_compound",
    "salac_berry": "salac_berry",
    "sand_silica": "sand_silica",
    "saw_dust": "saw_dust",
    "shiny_stone": "shiny_stone",
    "sweet_sap": "sweet_sap",
    "tiny_mushroom": "tiny_mushroom",
    "tin_ore": "tin_ore",
    "tomato": "tomato",
    "wood": "wood",
    "bronze_alloy": "bronze_alloy",
    "chemical_base": "chemical_base",
    "coal": "coal",
    "electrum_alloy": "electrum_alloy",
    "glass_bottle": "glass_bottle",
    "hardened_alloy": "hardened_alloy",
    "nickel": "nickel",
    "paint_splint": "paint_splint",
    "plastic": "plastic",
    "steel_alloy": "steel_alloy",
    "timber": "timber",
    "tin": "tin",
    "tint_black": "tint_black",
    "tint_blue": "tint_blue",
    "tint_green": "tint_green",
    "tint_orange": "tint_orange",
    "tint_purple": "tint_purple",
    "tint_red": "tint_red",
    "tint_white": "tint_white",
    "tint_yellow": "tint_yellow",
    "woven_thread": "woven_thread",
    "advanced_electronics_module": "advanced_electronics_module",
    "antidote_reactive": "antidote_reactive",
    "big_battery": "big_battery",
    "big_cpu": "big_cpu",
    "bolt_nut": "bolt_nut",
    "bronze_nectar": "bronze_nectar",
    "cable": "cable",
    "calibrated_weight": "calibrated_weight",
    "chemical_essence": "chemical_essence",
    "chemical_resuscitant": "chemical_resuscitant",
    "chip": "chip",
    "electronics_module": "electronics_module",
    "fat_monitor": "fat_monitor",
    "flat_monitor": "flat_monitor",
    "gear": "gear",
    "golden_nectar": "golden_nectar",
    "gpu": "gpu",
    "industrial_electronics": "industrial_electronics",
    "medicinal_extract": "medicinal_extract",
    "metal_container": "metal_container",
    "metal_frame": "metal_frame",
    "motherboard": "motherboard",
    "nails": "nails",
    "npu": "npu",
    "nuclear_waste": "nuclear_waste",
    "optical_lens": "optical_lens",
    "optic_fiber": "optic_fiber",
    "organic_fertilizer": "organic_fertilizer",
    "paint_coating": "paint_coating",
    "plastic_shell": "plastic_shell",
    "reinforced_container": "reinforced_container",
    "reinforced_plastic_shell": "reinforced_plastic_shell",
    "reinforced_strap": "reinforced_strap",
    "rubber_gasket": "rubber_gasket",
    "screen": "screen",
    "sensor": "sensor",
    "sensor_crystal": "sensor_crystal",
    "silver_nectar": "silver_nectar",
    "small_antenna": "small_antenna",
    "small_battery": "small_battery",
    "small_cpu": "small_cpu",
    "small_monitor": "small_monitor",
    "spring": "spring",
    "sweet_syrup": "sweet_syrup",
    "transistor": "transistor",
    "3d_printer": "3d_printer",
    "advanced_workbench": "advanced_workbench",
    "alembic": "alembic",
    "antenna": "antenna",
    "antimatter_generator": "antimatter_generator",
    "big_antenna": "big_antenna",
    "binoculars": "binoculars",
    "camera": "camera",
    "charcoal": "charcoal",
    "choice_scarf": "choice_scarf",
    "choice_specs": "choice_specs",
    "coal_generator": "coal_generator",
    "cooking_pot": "cooking_pot",
    "dive_ball": "dive_ball",
    "dragon_fang": "dragon_fang",
    "dragon_scale": "dragon_scale",
    "Escama Dragón": "dragon_scale",
    "energy_modulator": "energy_modulator",
    "eviolite": "eviolite",
    "food_dispenser": "food_dispenser",
    "food_grinder": "food_grinder",
    "food_processor": "food_processor",
    "full_restore": "full_restore",
    "furnace": "furnace",
    "industrial_battery": "industrial_battery",
    "lab_equipment": "lab_equipment",
    "lapidary_machine": "lapidary_machine",
    "laser_cutter": "laser_cutter",
    "life_orb": "life_orb",
    "luxury_ball": "luxury_ball",
    "medical_device": "medical_device",
    "microscope": "microscope",
    "miracle_seed": "miracle_seed",
    "mystic_water": "mystic_water",
    "nest_ball": "nest_ball",
    "nuclear_generator": "nuclear_generator",
    "poison_barb": "poison_barb",
    "pokedex": "pokedex",
    "pp_max": "pp_max",
    "quick_ball": "quick_ball",
    "radar": "radar",
    "rock_grinder": "rock_grinder",
    "scale": "scale",
    "server": "server",
    "silver_powder": "silver_powder",
    "smelter": "smelter",
    "solar_panel": "solar_panel",
    "weather_station": "weather_station",
    "woodcutting_machine": "woodcutting_machine",
    "workbench": "workbench",
    "bicycle": "bicycle"
  }'::jsonb;

  -- Crear conjunto de IDs válidos
  v_valid_ids := '{
    "berry_bronze": true, "berry_silver": true, "berry_gold": true, "everstone": true, "destiny_knot": true,
    "vigor_restorer": true, "power_weight": true, "power_bracer": true, "power_belt": true, "power_lens": true,
    "power_band": true, "power_anklet": true, "pokeball": true, "great_ball": true, "ultra_ball": true,
    "net_ball": true, "dusk_ball": true, "timer_ball": true, "master_ball": true, "potion": true,
    "super_potion": true, "hyper_potion": true, "max_potion": true, "soda_pop": true, "lemonade": true,
    "revive": true, "revive_max": true, "antidoto": true, "burn_heal": true, "awakening": true,
    "full_heal": true, "ether": true, "elixir": true, "elixir_max": true, "fire_stone": true,
    "water_stone": true, "thunder_stone": true, "leaf_stone": true, "moon_stone": true, "sun_stone": true,
    "exp_share": true, "leftovers": true, "shell_bell": true, "choice_band": true, "focus_sash": true,
    "scope_lens": true, "magnet": true, "rare_candy": true, "vigor_candy": true, "move_relearner": true,
    "nature_patch": true, "ability_pill": true, "ticket_shiny": true, "amulet_coin": true, "ticket_safari": true,
    "ticket_cerulean": true, "incense_fire": true, "incense_water": true, "incense_grass": true, "incense_normal": true,
    "incense_ghost": true, "incense_psychic": true, "pp_up": true, "lucky_egg": true, "repel": true,
    "super_repel": true, "max_repel": true, "fishing_rod": true, "fishing_rod_good": true, "fishing_rod_super": true,
    "pickaxe": true, "pickaxe_silver": true, "pickaxe_gold": true, "brush": true, "brush_good": true,
    "brush_super": true, "helix_fossil": true, "dome_fossil": true, "old_amber": true, "nugget": true,
    "pearl": true, "big_pearl": true, "stardust": true, "star_piece": true, "coal_ore": true,
    "copper_ore": true, "iron_ore": true, "silver_ore": true, "gold_ore": true, "tungsten_ore": true,
    "uranium_ore": true, "rubi_ore": true, "zaphire_ore": true, "emmerald_ore": true, "topaz_ore": true,
    "diamond_ore": true, "copper": true, "iron": true, "silver": true, "gold": true,
    "tungsten": true, "uranium": true, "rubi": true, "zaphire": true, "emmerald": true,
    "topaz": true, "diamond": true, "light_ball": true, "thick_club": true, "stick": true,
    "metal_powder": true, "twisted_spoon": true, "spell_tag": true, "ticket_articuno": true, "ticket_mewtwo": true,
    "iv_scanner": true, "tm01": true, "tm02": true, "tm03": true, "tm04": true,
    "tm05": true, "tm06": true, "tm07": true, "tm08": true, "tm09": true,
    "tm10": true, "tm11": true, "tm12": true, "tm13": true, "tm14": true,
    "tm15": true, "tm16": true, "tm17": true, "tm18": true, "tm19": true,
    "tm20": true, "tm21": true, "tm22": true, "tm23": true, "tm24": true,
    "tm25": true, "tm26": true, "tm27": true, "tm28": true, "tm29": true,
    "tm30": true, "tm31": true, "tm32": true, "tm33": true, "tm34": true,
    "tm35": true, "tm36": true, "tm37": true, "tm38": true, "tm39": true,
    "tm40": true, "tm41": true, "tm42": true, "tm43": true, "tm44": true,
    "tm45": true, "tm46": true, "tm47": true, "tm48": true, "tm49": true,
    "tm50": true, "acid": true, "apricorn_blue": true, "apricorn_red": true, "apricorn_yellow": true,
    "berry_sugar": true, "bone_fragment": true, "broccoli": true, "carrot": true, "cloth": true,
    "combee_honey": true, "dawn_stone": true, "dusk_stone": true, "electronic_scrap": true, "energy_powder": true,
    "food_scraps": true, "fresh_water": true, "herb_rare": true, "ice_crystal": true, "ice_stone": true,
    "leather_strip": true, "lettuce": true, "liechi_berry": true, "metal_scrap": true, "mushroom": true,
    "nickel_ore": true, "oil": true, "onion": true, "pecha_berry_wild": true, "petrified_sap": true,
    "pigment_black": true, "pigment_blue": true, "pigment_green": true, "pigment_orange": true, "pigment_purple": true,
    "pigment_red": true, "pigment_white": true, "pigment_yellow": true, "potato": true, "revive_root": true,
    "rubber_compound": true, "salac_berry": true, "sand_silica": true, "saw_dust": true, "shiny_stone": true,
    "sweet_sap": true, "tiny_mushroom": true, "tin_ore": true, "tomato": true, "wood": true,
    "bronze_alloy": true, "chemical_base": true, "coal": true, "electrum_alloy": true, "glass_bottle": true,
    "hardened_alloy": true, "nickel": true, "paint_splint": true, "plastic": true, "steel_alloy": true,
    "timber": true, "tin": true, "tint_black": true, "tint_blue": true, "tint_green": true,
    "tint_orange": true, "tint_purple": true, "tint_red": true, "tint_white": true, "tint_yellow": true,
    "woven_thread": true, "advanced_electronics_module": true, "antidote_reactive": true, "big_battery": true, "big_cpu": true,
    "bolt_nut": true, "bronze_nectar": true, "cable": true, "calibrated_weight": true, "chemical_essence": true,
    "chemical_resuscitant": true, "chip": true, "electronics_module": true, "fat_monitor": true, "flat_monitor": true,
    "gear": true, "golden_nectar": true, "gpu": true, "industrial_electronics": true, "medicinal_extract": true,
    "metal_container": true, "metal_frame": true, "motherboard": true, "nails": true, "npu": true,
    "nuclear_waste": true, "optical_lens": true, "optic_fiber": true, "organic_fertilizer": true, "paint_coating": true,
    "plastic_shell": true, "reinforced_container": true, "reinforced_plastic_shell": true, "reinforced_strap": true, "rubber_gasket": true,
    "screen": true, "sensor": true, "sensor_crystal": true, "silver_nectar": true, "small_antenna": true,
    "small_battery": true, "small_cpu": true, "small_monitor": true, "spring": true, "sweet_syrup": true,
    "transistor": true, "3d_printer": true, "advanced_workbench": true, "alembic": true, "antenna": true,
    "antimatter_generator": true, "big_antenna": true, "binoculars": true, "camera": true, "charcoal": true,
    "choice_scarf": true, "choice_specs": true, "coal_generator": true, "cooking_pot": true, "dive_ball": true,
    "dragon_fang": true, "dragon_scale": true, "energy_modulator": true, "eviolite": true, "food_dispenser": true,
    "food_grinder": true, "food_processor": true, "full_restore": true, "furnace": true, "industrial_battery": true,
    "lab_equipment": true, "lapidary_machine": true, "laser_cutter": true, "life_orb": true, "luxury_ball": true,
    "medical_device": true, "microscope": true, "miracle_seed": true, "mystic_water": true, "nest_ball": true,
    "nuclear_generator": true, "poison_barb": true, "pokedex": true, "pp_max": true, "quick_ball": true,
    "radar": true, "rock_grinder": true, "scale": true, "server": true, "silver_powder": true,
    "smelter": true, "solar_panel": true, "weather_station": true, "woodcutting_machine": true, "workbench": true,
    "bicycle": true
  }'::jsonb;

  FOR r IN SELECT user_id, save_data FROM public.game_saves LOOP
    v_inventory := r.save_data -> 'inventory';
    
    IF v_inventory IS NOT NULL AND jsonb_typeof(v_inventory) = 'object' THEN
      v_new_inventory := '{}'::jsonb;
      
      FOR v_item_key, v_item_qty IN SELECT * FROM jsonb_each_text(v_inventory) LOOP
        -- Buscar traducción directa
        v_mapped_id := v_mapping ->> v_item_key;
        
        -- Si no está mapeado, verificar si ya es un ID válido o si es 'bicycle'
        IF v_mapped_id IS NULL THEN
          IF v_valid_ids ->> v_item_key IS NOT NULL THEN
            v_mapped_id := v_item_key;
          ELSE
            -- Si no es ID válido ni traducible, lanzar excepción para resolución manual (política estricta)
            RAISE EXCEPTION 'Item inválido o no traducible en save de user_id %: Key "%". Abortando migración.', r.user_id, v_item_key;
          END IF;
        END IF;
        
        -- Agregar al nuevo inventario
        v_new_inventory := jsonb_set(v_new_inventory, ARRAY[v_mapped_id], to_jsonb(v_item_qty::INTEGER));
      END LOOP;
      
      -- Actualizar save_data con el nuevo inventario
      UPDATE public.game_saves
      SET save_data = jsonb_set(r.save_data, '{inventory}', v_new_inventory)
      WHERE user_id = r.user_id;
    END IF;
  END LOOP;

  -- Actualizar db_version = 3 en profiles
  UPDATE public.profiles
  SET db_version = 3;

  -- Cambiar el valor por defecto para futuros nuevos perfiles a 3
  ALTER TABLE public.profiles ALTER COLUMN db_version SET DEFAULT 3;
END $$;

-- Actualizar system_config a la versión 20260611120000
INSERT INTO public.system_config (key, value) VALUES ('db_version', '20260611120000'::jsonb) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
