-- =====================================================
-- POKÉ VICIO — MIGRACIÓN DE SAVES: NORMALIZACIÓN DE ÍTEMS V3
-- Fecha: 2026-06-29
-- Descripción: Normaliza todos los IDs de objetos en la mochila (inventory) de los saves a IDs de Showdown puros usando un mapa de traducción preciso.
-- =====================================================

DO $$
DECLARE
  r RECORD;
  v_save_data JSONB;
  v_inventory JSONB;
  v_new_inventory JSONB;
  v_inv_key TEXT;
  v_inv_val INT;
  v_clean_key TEXT;
  v_items_map JSONB;
BEGIN
  -- Definir mapa preciso de conversión y restauración
  v_items_map := '{
  "3dprinter": "3d_printer",
  "abilitypill": "ability_pill",
  "absorbbulb": "absorb_bulb",
  "advancedelectronicsmodule": "advanced_electronics_module",
  "advancedworkbench": "advanced_workbench",
  "aguavberry": "aguav_berry",
  "airballoon": "air_balloon",
  "amuletcoin": "amulet_coin",
  "anti-parálisis": "paralyze_heal",
  "antidotereactive": "antidote_reactive",
  "antimattergenerator": "antimatter_generator",
  "antídoto": "antidote",
  "apicotberry": "apicot_berry",
  "apricornblue": "apricorn_blue",
  "apricornred": "apricorn_red",
  "apricornyellow": "apricorn_yellow",
  "aspearberry": "aspear_berry",
  "auspiciousarmor": "auspicious_armor",
  "babiriberry": "babiri_berry",
  "baya de bronce": "berry_bronze",
  "baya de oro": "berry_gold",
  "baya de plata": "berry_silver",
  "beast_ball": "beastball",
  "berrybronze": "berry_bronze",
  "berrygold": "berry_gold",
  "berrysilver": "berry_silver",
  "berrysugar": "berry_sugar",
  "bigantenna": "big_antenna",
  "bigbattery": "big_battery",
  "bigcpu": "big_cpu",
  "bigpearl": "big_pearl",
  "bindingband": "binding_band",
  "blacksludge": "black_sludge",
  "boltnut": "bolt_nut",
  "bonefragment": "bone_fragment",
  "boosterenergy": "booster_energy",
  "bronzealloy": "bronze_alloy",
  "bronzenectar": "bronze_nectar",
  "brushgood": "brush_good",
  "brushsuper": "brush_super",
  "burnheal": "burn_heal",
  "calibratedweight": "calibrated_weight",
  "cellbattery": "cell_battery",
  "chartiberry": "charti_berry",
  "chemicalbase": "chemical_base",
  "chemicalessence": "chemical_essence",
  "chemicalresuscitant": "chemical_resuscitant",
  "cheriberry": "cheri_berry",
  "cherish_ball": "cherishball",
  "chestoberry": "chesto_berry",
  "chilanberry": "chilan_berry",
  "chippedpot": "chipped_pot",
  "choiceband": "choice_band",
  "choicescarf": "choice_scarf",
  "choicespecs": "choice_specs",
  "chopleberry": "chople_berry",
  "clearamulet": "clear_amulet",
  "coalgenerator": "coal_generator",
  "coalore": "coal_ore",
  "cobaberry": "coba_berry",
  "colburberry": "colbur_berry",
  "combeehoney": "combee_honey",
  "cookingpot": "cooking_pot",
  "copperore": "copper_ore",
  "cornerstonemask": "cornerstone_mask",
  "covertcloak": "covert_cloak",
  "crackedpot": "cracked_pot",
  "cura total": "full_heal",
  "custapberry": "custap_berry",
  "damprock": "damp_rock",
  "dawnstone": "dawn_stone",
  "deshielo": "ice_heal",
  "despertar": "awakening",
  "destinyknot": "destiny_knot",
  "diamondore": "diamond_ore",
  "dive_ball": "diveball",
  "domefossil": "dome_fossil",
  "dracoplate": "draco_plate",
  "dragonfang": "dragon_fang",
  "dragonscale": "dragon_scale",
  "dreadplate": "dread_plate",
  "dream_ball": "dreamball",
  "dubiousdisc": "dubious_disc",
  "dusk_ball": "duskball",
  "duskstone": "dusk_stone",
  "earthplate": "earth_plate",
  "ejectbutton": "eject_button",
  "ejectpack": "eject_pack",
  "electricseed": "electric_seed",
  "electronicscrap": "electronic_scrap",
  "electronicsmodule": "electronics_module",
  "electrumalloy": "electrum_alloy",
  "elixirmax": "elixir_max",
  "emmeraldore": "emmerald_ore",
  "energymodulator": "energy_modulator",
  "energypowder": "energy_powder",
  "enigmaberry": "enigma_berry",
  "expshare": "exp_share",
  "fairyfeather": "fairy_feather",
  "fast_ball": "fastball",
  "fatmonitor": "fat_monitor",
  "figyberry": "figy_berry",
  "firestone": "fire_stone",
  "fishingrod": "fishing_rod",
  "fishingrodgood": "fishing_rod_good",
  "fishingrodsuper": "fishing_rod_super",
  "fistplate": "fist_plate",
  "flameorb": "flame_orb",
  "flameplate": "flame_plate",
  "flatmonitor": "flat_monitor",
  "floatstone": "float_stone",
  "focusband": "focus_band",
  "focussash": "focus_sash",
  "fooddispenser": "food_dispenser",
  "foodgrinder": "food_grinder",
  "foodprocessor": "food_processor",
  "foodscraps": "food_scraps",
  "freshwater": "fresh_water",
  "friend_ball": "friendball",
  "fullheal": "full_heal",
  "fullrestore": "full_restore",
  "fósil domo": "dome_fossil",
  "fósil hélix": "helix_fossil",
  "galaricacuff": "galarica_cuff",
  "galaricawreath": "galarica_wreath",
  "ganlonberry": "ganlon_berry",
  "glassbottle": "glass_bottle",
  "goldennectar": "golden_nectar",
  "goldore": "gold_ore",
  "grassyseed": "grassy_seed",
  "great_ball": "greatball",
  "grepaberry": "grepa_berry",
  "gripclaw": "grip_claw",
  "habanberry": "haban_berry",
  "hardenedalloy": "hardened_alloy",
  "hardstone": "hard_stone",
  "heal_ball": "healball",
  "hearthflamemask": "hearthflame_mask",
  "heatrock": "heat_rock",
  "heavy_ball": "heavyball",
  "heavydutyboots": "heavy_duty_boots",
  "helixfossil": "helix_fossil",
  "herbrare": "herb_rare",
  "hiperpoción": "hyper_potion",
  "hondewberry": "hondew_berry",
  "hyperpotion": "hyper_potion",
  "iapapaberry": "iapapa_berry",
  "icecrystal": "ice_crystal",
  "iceheal": "ice_heal",
  "icestone": "ice_stone",
  "icicleplate": "icicle_plate",
  "icyrock": "icy_rock",
  "incensefire": "incense_fire",
  "incenseghost": "incense_ghost",
  "incensegrass": "incense_grass",
  "incensenormal": "incense_normal",
  "incensepsychic": "incense_psychic",
  "incensewater": "incense_water",
  "industrialbattery": "industrial_battery",
  "industrialelectronics": "industrial_electronics",
  "insectplate": "insect_plate",
  "ironore": "iron_ore",
  "ironplate": "iron_plate",
  "ivscanner": "iv_scanner",
  "jabocaberry": "jaboca_berry",
  "kasibberry": "kasib_berry",
  "kebiaberry": "kebia_berry",
  "keeberry": "kee_berry",
  "kelpsyberry": "kelpsy_berry",
  "labequipment": "lab_equipment",
  "lansatberry": "lansat_berry",
  "lapidarymachine": "lapidary_machine",
  "lasercutter": "laser_cutter",
  "leafstone": "leaf_stone",
  "leatherstrip": "leather_strip",
  "leppaberry": "leppa_berry",
  "level_ball": "levelball",
  "liechiberry": "liechi_berry",
  "lifeorb": "life_orb",
  "light_ball": "lightball",
  "lightclay": "light_clay",
  "loadeddice": "loaded_dice",
  "love_ball": "loveball",
  "luckyegg": "lucky_egg",
  "lumberry": "lum_berry",
  "luminousmoss": "luminous_moss",
  "lure_ball": "lureball",
  "luxury_ball": "luxuryball",
  "magoberry": "mago_berry",
  "maliciousarmor": "malicious_armor",
  "marangaberry": "maranga_berry",
  "master_ball": "masterball",
  "masterpieceteacup": "masterpiece_teacup",
  "max poción": "max_potion",
  "max revivir": "revive_max",
  "maxpotion": "max_potion",
  "maxrepel": "max_repel",
  "meadowplate": "meadow_plate",
  "medicaldevice": "medical_device",
  "medicinalextract": "medicinal_extract",
  "metalcoat": "metal_coat",
  "metalcontainer": "metal_container",
  "metalframe": "metal_frame",
  "metalpowder": "metal_powder",
  "metalscrap": "metal_scrap",
  "micleberry": "micle_berry",
  "mindplate": "mind_plate",
  "mineral de carbón": "coal_ore",
  "mineral de cobre": "copper_ore",
  "mineral de hierro": "iron_ore",
  "mineral de wolframio": "tungsten_ore",
  "miracleseed": "miracle_seed",
  "mirrorherb": "mirror_herb",
  "mistyseed": "misty_seed",
  "moon_ball": "moonball",
  "moonstone": "moon_stone",
  "moverelearner": "move_relearner",
  "mysticwater": "mystic_water",
  "naturepatch": "nature_patch",
  "nest_ball": "nestball",
  "net_ball": "netball",
  "nickelore": "nickel_ore",
  "normalgem": "normal_gem",
  "nucleargenerator": "nuclear_generator",
  "nuclearwaste": "nuclear_waste",
  "occaberry": "occa_berry",
  "oldamber": "old_amber",
  "opticallens": "optical_lens",
  "opticfiber": "optic_fiber",
  "oranberry": "oran_berry",
  "organicfertilizer": "organic_fertilizer",
  "ovalstone": "oval_stone",
  "paintcoating": "paint_coating",
  "paintsplint": "paint_splint",
  "paralyzeheal": "paralyze_heal",
  "park_ball": "parkball",
  "passhoberry": "passho_berry",
  "payapaberry": "payapa_berry",
  "pechaberry": "pecha_berry",
  "pechaberrywild": "pecha_berry_wild",
  "perla": "pearl",
  "perla grande": "big_pearl",
  "persimberry": "persim_berry",
  "petayaberry": "petaya_berry",
  "petrifiedsap": "petrified_sap",
  "pickaxegold": "pickaxe_gold",
  "pickaxesilver": "pickaxe_silver",
  "piedra agua": "water_stone",
  "piedra fuego": "fire_stone",
  "piedra hoja": "leaf_stone",
  "piedra lunar": "moon_stone",
  "piedra solar": "sun_stone",
  "piedra trueno": "thunder_stone",
  "pigmentblack": "pigment_black",
  "pigmentblue": "pigment_blue",
  "pigmentgreen": "pigment_green",
  "pigmentorange": "pigment_orange",
  "pigmentpurple": "pigment_purple",
  "pigmentred": "pigment_red",
  "pigmentwhite": "pigment_white",
  "pigmentyellow": "pigment_yellow",
  "pixieplate": "pixie_plate",
  "plasticshell": "plastic_shell",
  "poción": "potion",
  "poisonbarb": "poison_barb",
  "poke_radar": "radar",
  "pokeball_de_prueba": "pokeball",
  "pokebola": "pokeball",
  "pokeradar": "radar",
  "pokéball": "pokeball",
  "polvo estelar": "stardust",
  "pomegberry": "pomeg_berry",
  "poweranklet": "power_anklet",
  "powerband": "power_band",
  "powerbelt": "power_belt",
  "powerbracer": "power_bracer",
  "powerherb": "power_herb",
  "powerlens": "power_lens",
  "powerweight": "power_weight",
  "ppmax": "pp_max",
  "ppup": "pp_up",
  "premier_ball": "premierball",
  "prismscale": "prism_scale",
  "protectivepads": "protective_pads",
  "psychicseed": "psychic_seed",
  "punchingglove": "punching_glove",
  "qualotberry": "qualot_berry",
  "quick_ball": "quickball",
  "rarecandy": "rare_candy",
  "rawstberry": "rawst_berry",
  "razorclaw": "razor_claw",
  "razorfang": "razor_fang",
  "reapercloth": "reaper_cloth",
  "redcard": "red_card",
  "reinforcedcontainer": "reinforced_container",
  "reinforcedplasticshell": "reinforced_plastic_shell",
  "reinforcedstrap": "reinforced_strap",
  "repeat_ball": "repeatball",
  "restaurar todo": "full_restore",
  "revivemax": "revive_max",
  "reviveroot": "revive_root",
  "revivir": "revive",
  "rindoberry": "rindo_berry",
  "ringtarget": "ring_target",
  "rockgrinder": "rock_grinder",
  "roomservice": "room_service",
  "roseliberry": "roseli_berry",
  "rowapberry": "rowap_berry",
  "rubbercompound": "rubber_compound",
  "rubbergasket": "rubber_gasket",
  "rubiore": "rubi_ore",
  "safari_ball": "safariball",
  "safetygoggles": "safety_goggles",
  "salacberry": "salac_berry",
  "sandsilica": "sand_silica",
  "sawdust": "saw_dust",
  "scopelens": "scope_lens",
  "sensorcrystal": "sensor_crystal",
  "shedshell": "shed_shell",
  "shellbell": "shell_bell",
  "shinystone": "shiny_stone",
  "shucaberry": "shuca_berry",
  "silvernectar": "silver_nectar",
  "silverore": "silver_ore",
  "silverpowder": "silver_powder",
  "sitrusberry": "sitrus_berry",
  "skyplate": "sky_plate",
  "smallantenna": "small_antenna",
  "smallbattery": "small_battery",
  "smallcpu": "small_cpu",
  "smallmonitor": "small_monitor",
  "smoothrock": "smooth_rock",
  "sodapop": "soda_pop",
  "solarpanel": "solar_panel",
  "souldew": "soul_dew",
  "spelltag": "spell_tag",
  "splashplate": "splash_plate",
  "spookyplate": "spooky_plate",
  "sport_ball": "sportball",
  "starfberry": "starf_berry",
  "starpiece": "star_piece",
  "steelalloy": "steel_alloy",
  "stickybarb": "sticky_barb",
  "stoneplate": "stone_plate",
  "sunstone": "sun_stone",
  "superpotion": "super_potion",
  "superrepel": "super_repel",
  "sweetapple": "sweet_apple",
  "sweetsap": "sweet_sap",
  "sweetsyrup": "sweet_syrup",
  "syrupyapple": "syrupy_apple",
  "súper ball": "superball",
  "súper poción": "super_potion",
  "tamatoberry": "tamato_berry",
  "tangaberry": "tanga_berry",
  "tartapple": "tart_apple",
  "terrainextender": "terrain_extender",
  "thickclub": "thick_club",
  "throatspray": "throat_spray",
  "thunderstone": "thunder_stone",
  "ticketarticuno": "ticket_articuno",
  "ticketcerulean": "ticket_cerulean",
  "ticketmewtwo": "ticket_mewtwo",
  "ticketsafari": "ticket_safari",
  "ticketshiny": "ticket_shiny",
  "timer_ball": "timerball",
  "tinore": "tin_ore",
  "tintblack": "tint_black",
  "tintblue": "tint_blue",
  "tintgreen": "tint_green",
  "tintorange": "tint_orange",
  "tintpurple": "tint_purple",
  "tintred": "tint_red",
  "tintwhite": "tint_white",
  "tintyellow": "tint_yellow",
  "tinymushroom": "tiny_mushroom",
  "topazore": "topaz_ore",
  "toxicorb": "toxic_orb",
  "toxicplate": "toxic_plate",
  "tungstenore": "tungsten_ore",
  "twistedspoon": "twisted_spoon",
  "ultra_ball": "ultraball",
  "unremarkableteacup": "unremarkable_teacup",
  "uraniumore": "uranium_ore",
  "utilityumbrella": "utility_umbrella",
  "vigorcandy": "vigor_candy",
  "vigorrestorer": "vigor_restorer",
  "wacanberry": "wacan_berry",
  "waterstone": "water_stone",
  "weatherstation": "weather_station",
  "wellspringmask": "wellspring_mask",
  "wikiberry": "wiki_berry",
  "woodcuttingmachine": "woodcutting_machine",
  "woventhread": "woven_thread",
  "yacheberry": "yache_berry",
  "zaphireore": "zaphire_ore",
  "zapplate": "zap_plate",
  "ámbar viejo": "old_amber"
}'::jsonb;

  -- 1. Procesar game_saves
  FOR r IN SELECT user_id, save_data FROM public.game_saves LOOP
    v_save_data := r.save_data;
    v_inventory := v_save_data -> 'inventory';

    IF v_inventory IS NOT NULL AND jsonb_typeof(v_inventory) = 'object' THEN
      v_new_inventory := '{}'::jsonb;
      FOR v_inv_key, v_inv_val IN SELECT * FROM jsonb_each_text(v_inventory) LOOP
        -- Normalizar clave usando minúsculas y buscar en mapa
        v_clean_key := lower(v_inv_key);
        
        IF v_items_map ->> v_clean_key IS NOT NULL THEN
          v_clean_key := v_items_map ->> v_clean_key;
        END IF;

        -- Sumar en caso de colisión
        IF v_new_inventory ->> v_clean_key IS NOT NULL THEN
          v_new_inventory := jsonb_set(v_new_inventory, array[v_clean_key], to_jsonb((v_new_inventory ->> v_clean_key)::int + v_inv_val));
        ELSE
          v_new_inventory := jsonb_set(v_new_inventory, array[v_clean_key], to_jsonb(v_inv_val), true);
        END IF;
      END LOOP;

      v_save_data := jsonb_set(v_save_data, '{inventory}', v_new_inventory);

      -- Escribir de vuelta
      UPDATE public.game_saves
      SET save_data = v_save_data
      WHERE user_id = r.user_id;
    END IF;
  END LOOP;

  -- 2. Actualizar db_version
  INSERT INTO public.system_config (key, value) 
  VALUES ('db_version', '20260629230200'::jsonb) 
  ON CONFLICT (key) 
  DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

END $$;
