-- SQLite Migration: 20260828114000_fix_event_enabled_species
-- Description: Updates weekly event rotations in events_config to ensure 100% of participating species belong strictly to ENABLED_POKEMON_IDS.

UPDATE events_config
SET config = '{"hasCompetition": true, "requireCaughtDuringEvent": true, "rotationTheme": "weekly_4", "speciesShinyMult": 3.0, "speciesRateMult": 2.0, "fishingMult": 2.0, "minigameBuffs": {"fishing": {"encounterRateMult": 2.0, "rareDropMult": 1.5, "shinyMult": 3.0}}, "weeklyRotations": {"1": {"species": "magikarp,gyarados", "banner": "hora_magikarp_full", "title": "Torneo Magikarp & Gyarados"}, "2": {"species": "shellder,staryu,horsea,seadra,goldeen", "banner": "pesca_exotica_full", "title": "Torneo de Pesca Exótica"}, "3": {"species": "tentacool,tentacruel,krabby,kingler,poliwag", "banner": "pesca_profunda_full", "title": "Torneo de Pesca Profunda"}, "4": {"species": "dratini,dragonair,lapras", "banner": "pesca_mistica_full", "title": "Torneo de Pesca Mística"}}, "subCompetitions": [{"id": "ivs", "name": "Genética Superior (IVs)", "metric": "total_ivs", "order": "max", "prizes": {"first": {"type": "mixed", "money": 25000, "battleCoins": 150, "items": {"goldbottlecap": 1, "rarecandy": 5}}, "second": {"type": "mixed", "money": 15000, "battleCoins": 100, "items": {"bottlecap": 2, "rarecandy": 3}}, "third": {"type": "mixed", "money": 8000, "battleCoins": 50, "items": {"bottlecap": 1, "rarecandy": 1}}}}, {"id": "weight", "name": "Masa y Peso (Titán / Miniatura)", "metric": "weight", "order": "auto", "prizes": {"first": {"type": "mixed", "money": 25000, "battleCoins": 150, "items": {"bigpearl": 3, "lureball": 10}}, "second": {"type": "mixed", "money": 15000, "battleCoins": 100, "items": {"bigpearl": 2, "netball": 10}}, "third": {"type": "mixed", "money": 8000, "battleCoins": 50, "items": {"pearl": 3, "diveball": 5}}}}, {"id": "height", "name": "Envergadura y Altura (Gran Salto)", "metric": "height", "order": "auto", "prizes": {"first": {"type": "mixed", "money": 25000, "battleCoins": 150, "items": {"waterstone": 2, "dragonscale": 1, "mysticwater": 1}}, "second": {"type": "mixed", "money": 15000, "battleCoins": 100, "items": {"waterstone": 1, "damprock": 1}}, "third": {"type": "mixed", "money": 8000, "battleCoins": 50, "items": {"waterstone": 1}}}}]}'
WHERE id = 'torneo_pesca';

UPDATE events_config
SET config = '{"hasCompetition": true, "requireCaughtDuringEvent": true, "rotationTheme": "weekly_4", "speciesShinyMult": 3.0, "speciesRateMult": 2.0, "weeklyRotations": {"1": {"species": "scyther,pinsir,butterfree,beedrill,venomoth", "banner": "caza_bichos_full", "title": "Concurso de Caza de Bichos"}, "2": {"species": "tauros,kangaskhan,chansey,dodrio", "banner": "safari_park_full", "title": "Gran Torneo de la Zona Safari"}, "3": {"species": "kabuto,omanyte,aerodactyl,geodude,onix,rhyhorn", "banner": "arqueologia_fosiles_full", "title": "Torneo de Excavación & Fósiles"}, "4": {"species": "gastly,haunter,gengar,zubat,golbat,hypno", "banner": "caza_nocturna_full", "title": "Caza Nocturna & Mística"}}, "subCompetitions": [{"id": "ivs", "name": "Genética Superior (IVs)", "metric": "total_ivs", "order": "max", "prizes": {"first": {"type": "mixed", "money": 25000, "battleCoins": 150, "items": {"goldbottlecap": 1, "rarecandy": 5}}, "second": {"type": "mixed", "money": 15000, "battleCoins": 100, "items": {"bottlecap": 2, "rarecandy": 3}}, "third": {"type": "mixed", "money": 8000, "battleCoins": 50, "items": {"bottlecap": 1, "rarecandy": 1}}}}, {"id": "weight", "name": "Masa y Peso (Titán / Miniatura)", "metric": "weight", "order": "auto", "prizes": {"first": {"type": "mixed", "money": 25000, "battleCoins": 150, "items": {"bigpearl": 3, "heavydutyboots": 1}}, "second": {"type": "mixed", "money": 15000, "battleCoins": 100, "items": {"bigpearl": 2, "floatstone": 1}}, "third": {"type": "mixed", "money": 8000, "battleCoins": 50, "items": {"pearl": 3}}}}, {"id": "height", "name": "Envergadura y Tamaño", "metric": "height", "order": "auto", "prizes": {"first": {"type": "mixed", "money": 25000, "battleCoins": 150, "items": {"leafstone": 2, "moonstone": 1, "sunstone": 1}}, "second": {"type": "mixed", "money": 15000, "battleCoins": 100, "items": {"leafstone": 1, "moonstone": 1}}, "third": {"type": "mixed", "money": 8000, "battleCoins": 50, "items": {"leafstone": 1}}}}]}'
WHERE id = 'torneo_caza';

INSERT INTO system_config (key, value) VALUES ('db_version', '"20260828114000"')
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP;
