/**
 * AUTO-GENERATED OFFICIAL SERVERS CONFIGURATION
 * Generated by scripts/configure_official_servers.ts
 * Last configured: 2026-08-30T04:11:12.131299072Z
 * 
 * Lista de servidores registrados para la GUI de Login.
 * Creado automáticamente a partir del archivo .env maestro.
 */

export interface OfficialServer {
  id: string; // domain-ok: Open dynamic text or non-domain string payload
  name: string; // domain-ok: Open dynamic text or non-domain string payload
  region: string; // domain-ok: Open dynamic text or non-domain string payload
  url: string; // domain-ok: Open dynamic text or non-domain string payload
  anonKey: string; // domain-ok: Open dynamic text or non-domain string payload
  isDefault?: boolean;
}

const TEST_DOCKER_SERVER: OfficialServer = {
  id: 'test_postgres',
  name: 'Local Docker Test Server',
  region: 'Testing',
  url: 'http://127.0.0.1:54321',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNjAwMDAwMDAwLCJleHAiOjI1MDAwMDAwMDB9.bWuWcdy1ICtTs7Zq7TNjum7G0VIS5je9rFlzshoeBLA'
};

export const OFFICIAL_SERVERS: OfficialServer[] = [
  {
    id: 'official_prod',
    name: 'Poké Vicio Oficial',
    region: 'Global',
    url: 'https://wakrkvizmoqdlrtnxcth.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indha3Jrdml6bW9xZGxydG54Y3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMDA3MjYsImV4cCI6MjA4ODg3NjcyNn0.l_NYYNPDFOAr5CRqbuVf3jLv_TRnOw6shw9j9GzhQsA',
    isDefault: true
  },
  {
    id: 'server_franco',
    name: 'Servidor Franco (Docker)',
    region: 'Desarrollo',
    url: 'https://francogp.myqnapcloud.com:50002',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzgwMTg4NjcyLCJleHAiOjE5Mzc4Njg2NzJ9.u9JvY3wUO9K9Kh4Pv8EzlOrwtwNA7mxzLC6y5bqSoVA'
  },
  TEST_DOCKER_SERVER
];

export const DEFAULT_SERVER = (OFFICIAL_SERVERS.find(s => s.isDefault) || OFFICIAL_SERVERS[0]) as OfficialServer;
