/**
 * OFFICIAL SERVERS CONFIGURATION (STABLE TYPED FACADE)
 * 
 * SSoT Architecture:
 * - Reads from gitignored `servers.local.json` generated by `configure_official_servers.ts`.
 * - Requires a master `.env` or CI/CD secrets.
 * - ZERO SILENT FALLBACK MANDATE: If servers.local.json is missing or empty, execution FAILS LOUDLY.
 * - NEVER modified directly by hand to avoid git pull conflicts on production / testing deploys.
 */

import localServersData from './servers.local.json' with { type: 'json' };

export interface OfficialServer {
  id: string; // domain-ok: Open dynamic text or non-domain string payload
  name: string; // domain-ok: Open dynamic text or non-domain string payload
  region: string; // domain-ok: Open dynamic text or non-domain string payload
  url: string; // domain-ok: Open dynamic text or non-domain string payload
  anonKey: string; // domain-ok: Open dynamic text or non-domain string payload
  isDefault?: boolean;
}

if (!Array.isArray(localServersData) || localServersData.length === 0) {
  throw new Error(
    '[official_servers] ERROR CRÍTICO: No se encontraron servidores configurados en servers.local.json. ' +
    'Es estrictamente obligatorio contar con un archivo .env maestro o secrets de CI/CD para compilar la configuración de servidores. ' +
    'Los fallbacks están estrictamente prohibidos. Ejecute "npm run servers:configure" con las variables de servidor correspondientes.'
  );
}

export const OFFICIAL_SERVERS: OfficialServer[] = [...localServersData];

const defaultFound = OFFICIAL_SERVERS.find((s) => s.isDefault) ?? OFFICIAL_SERVERS[0];
if (!defaultFound) {
  throw new Error('[official_servers] ERROR CRÍTICO: No existe ningún servidor válido marcado por defecto.');
}

export const DEFAULT_SERVER: OfficialServer = defaultFound;

export const OFFICIAL_SERVERS_BY_ID = Object.freeze(
  Object.fromEntries(OFFICIAL_SERVERS.map((s) => [s.id, s]))
);

