-- Global Chat (persistente) - maximo 50 mensajes
-- Ejecutar en Supabase SQL Editor

create table if not exists public.global_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 1 and 32),
  message text not null check (char_length(message) between 1 and 240),
  player_class text,
  trainer_level int not null default 1 check (trainer_level between 1 and 100),
  created_at timestamptz not null default now()
);

create index if not exists idx_global_chat_messages_created_at
  on public.global_chat_messages (created_at desc, id desc);

alter table public.global_chat_messages enable row level security;

drop policy if exists global_chat_select_all on public.global_chat_messages;
create policy global_chat_select_all
  on public.global_chat_messages
  for select
  to authenticated
  using (true);

drop policy if exists global_chat_insert_self on public.global_chat_messages;
create policy global_chat_insert_self
  on public.global_chat_messages
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and trainer_level >= 10
  );

grant select, insert on public.global_chat_messages to authenticated;
grant usage, select on sequence public.global_chat_messages_id_seq to authenticated;

create or replace function public.trim_global_chat_messages()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.global_chat_messages
  where id in (
    select id
    from public.global_chat_messages
    order by created_at desc, id desc
    offset 50
  );
  return null;
end;
$$;

drop trigger if exists trg_trim_global_chat_messages on public.global_chat_messages;
create trigger trg_trim_global_chat_messages
after insert on public.global_chat_messages
for each statement
execute function public.trim_global_chat_messages();

-- Realtime: agregar tabla a la publicacion de Supabase
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'global_chat_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.global_chat_messages;
  END IF;
EXCEPTION
  WHEN undefined_object THEN
    NULL;
END $$;
