import { DEFAULT_INITIAL_ELO, INITIAL_BALLS_COUNT, INITIAL_MONEY, INITIAL_POKEBALL_COUNT } from '@/logic/constants/gameplay.ts';
import type { GameState } from '@/types/system/game';

export const INITIAL_STATE: GameState = {
  trainer: '',
  gender: 'h',
  badges: 0,
  balls: INITIAL_BALLS_COUNT,
  money: INITIAL_MONEY,
  battleCoins: 0,
  eggs: [],
  trainerChance: 1,
  trainerLevel: 1,
  trainerExp: 0,
  trainerExpNeeded: 100,
  inventory: { potion: 3, pokeball: INITIAL_POKEBALL_COUNT },
  map: {
    currentMap: 'route1',
    region: 'kanto',
    lastNavigateAt: 0
  },
  team: [],
  box: [],
  pokedex: [],
  seenPokedex: [],
  defeatedGyms: [],
  gymProgress: {},
  lastGymWins: {},
  lastGymAttempts: {},
  battle: null,
  starterChosen: false,
  lastPokemonCenterHeal: 0,
  lastRankedSeason: null,
  nick_style: null,
  avatar_style: null,
  stats: {},
  eloRating: DEFAULT_INITIAL_ELO,
  pvpStats: { wins: 0, losses: 0, draws: 0 },
  rankedMaxElo: DEFAULT_INITIAL_ELO,
  rankedRewardsClaimed: [],
  passiveTeamUids: [],
  passiveTeamActive: false,
  activeBattle: null,
  daycare_missions: [],
  daycare_mission_refreshes: 3,
  safariTicketSecs: 0,
  ceruleanTicketSecs: 0,
  articunoTicketSecs: 0,
  mewtwoTicketSecs: 0,
  repelSecs: 0,
  fishingRodSecs: 0,
  fishingRodType: null,
  pickaxeSecs: 0,
  pickaxeType: null,
  brushSecs: 0,
  brushType: null,
  shinyBoostSecs: 0,
  amuletCoinSecs: 0,
  luckyEggSecs: 0,
  ivScannerSecs: 0,
  incenseType: null,
  incenseSecs: 0,
  daycare_berry_egg_time: 0,
  boxCount: 4,
  chats: {},
  playerClass: null,
  classLevel: 1,
  classXP: 0,
  classData: {
    captureStreak: 0,
    longestStreak: 0,
    reputation: 0,
    blackMarketSales: 0,
    criminality: 0,
    blackMarketDaily: { date: '', items: [], purchased: [] },
    extortedRouteId: null,
    extortedRouteTimestamp: null,
    lastEggScanDate: null
  },
  faction: null,
  warCoins: 0,
  warCoinsSpent: 0,
  warDailyCap: {},
  warDailyCoins: {},
  warMyPtsLocal: {},
  warPointsAccumulator: 0,
  lastResolvedWeek: '',
  notificationHistory: [],
  marketSoldSeenIds: [],
  claimQueue: [],
  pvpTeam: [],
  warTeam: [],
  warSlots: 6,
  guardianCaptures: {},
  playtime: 0
}
