/**
 * @file generate_migrations.js
 * @description Generador automático de manifiesto de migraciones SQL.
 * 
 * UTILIDAD: 
 * Escanea el directorio 'database/migrations/' en busca de archivos .sql y los 
 * empaqueta en un único archivo JavaScript ('src/logic/db/migrations_data.ts').
 * 
 * IMPORTANCIA: 
 * Este script es el puente entre el diseño de base de datos (SQL) y la lógica de ejecución (JS).
 * Permite que el DBRouter ejecute actualizaciones de esquema de forma determinista tanto en 
 * Supabase como en el SQLite local, manteniendo la "Triple Fuente de Verdad".
 * 
 * Se ejecuta automáticamente durante el proceso de build y en Hot Update mediante Vite.
 */

import fs from 'fs';
import path from 'path';

const MIGRATIONS_DIR = path.resolve(process.cwd(), 'database/migrations');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/logic/db/migrations_data.ts');

export function generateMigrations() {
  console.log('[Migrations Generator] Scanning directory:', MIGRATIONS_DIR);
  
  if (!fs.existsSync(MIGRATIONS_DIR)) {
    console.warn('[Migrations Generator] Migrations directory not found.');
    return;
  }

  // 1. Get all SQL files, excluding baseline if needed, but here we include all updates
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql') && !f.includes('baseline_schema')) // Baseline is handled by TABLES_SCHEMA
    .sort((a, b) => a.localeCompare(b));

  const migrations = files.map(filename => {
    const id = filename.replace('.sql', '');
    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, filename), 'utf-8');
    
    // Parse metadata from comments
    // Example: -- check: { "table": "profiles", "column": "role" }
    let check = null;
    const checkMatch = content.match(/--\s*check:\s*({.+})/);
    if (checkMatch) {
      try {
        check = JSON.parse(checkMatch[1]);
      } catch (e) {
        console.error(`[Migrations Generator] Error parsing check metadata in ${filename}:`, e);
      }
    }

    // Prepare SQL: remove comments and normalize newlines to keep it compact
    const sqlLines = content.split('\n')
      .map(line => {
        // Strip inline comments starting with --
        const commentIndex = line.indexOf('--');
        if (commentIndex !== -1) {
          // Keep part before comment, but only if it's not the 'check:' metadata line
          if (line.includes('check:')) return ''; 
          return line.substring(0, commentIndex);
        }
        return line;
      })
      .filter(line => line.trim().length > 0)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();

    return {
      id,
      sql: sqlLines,
      check
    };
  });

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate_migrations.js
 * Last generated: ${new Date().toISOString()}
 */

export const DATABASE_MIGRATIONS = ${JSON.stringify(migrations, null, 2)};
`;

  // Create directory if it doesn't exist
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`[Migrations Generator] Generated ${migrations.length} migrations in ${OUTPUT_FILE}`);
}

// Support running directly
const isDirectRun = process.argv[1] && (
  process.argv[1].endsWith('generate_migrations.ts') || 
  process.argv[1].includes('generate_migrations.ts')
);

if (isDirectRun) {
  generateMigrations();
}
