import fs from 'fs';
import path from 'path';

const MIGRATIONS_DIR = path.resolve(process.cwd(), 'database/migrations');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/logic/db/migrations_data.js');

export function generateMigrations() {
  console.log('[Migrations Generator] Scanning directory:', MIGRATIONS_DIR);
  
  if (!fs.existsSync(MIGRATIONS_DIR)) {
    console.warn('[Migrations Generator] Migrations directory not found.');
    return;
  }

  // 1. Get all SQL files, excluding baseline if needed, but here we include all updates
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql') && !f.includes('baseline_schema')) // Baseline is handled by TABLES_SCHEMA
    .sort((a, b) => a.localeCompare(b));

  const migrations = files.map(filename => {
    const id = filename.replace('.sql', '');
    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, filename), 'utf-8');
    
    // Parse metadata from comments
    // Example: -- check: { "table": "profiles", "column": "role" }
    let check = null;
    const checkMatch = content.match(/--\s*check:\s*({.+})/);
    if (checkMatch) {
      try {
        check = JSON.parse(checkMatch[1]);
      } catch (e) {
        console.error(`[Migrations Generator] Error parsing check metadata in ${filename}:`, e);
      }
    }

    // Prepare SQL: remove comments and normalize newlines to keep it compact
    const sqlLines = content.split('\n')
      .filter(line => !line.trim().startsWith('--'))
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();

    return {
      id,
      sql: sqlLines,
      check
    };
  });

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate_migrations.js
 * Last generated: ${new Date().toISOString()}
 */

export const DATABASE_MIGRATIONS = ${JSON.stringify(migrations, null, 2)};
`;

  // Create directory if it doesn't exist
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`[Migrations Generator] Generated ${migrations.length} migrations in ${OUTPUT_FILE}`);
}

// Support running directly
const isDirectRun = process.argv[1] && (
  process.argv[1].endsWith('generate_migrations.js') || 
  process.argv[1].includes('generate_migrations.js')
);

if (isDirectRun) {
  generateMigrations();
}
