/**
 * @file generate_migrations.js
 * @description Generador automático de manifiesto de migraciones SQL.
 * 
 * UTILIDAD: 
 * Escanea el directorio 'database/migrations/' en busca de archivos .sql y los 
 * empaqueta en un único archivo JavaScript ('src/logic/db/migrations_data.ts').
 * 
 * IMPORTANCIA: 
 * Este script es el puente entre el diseño de base de datos (SQL) y la lógica de ejecución (JS).
 * Permite que el DBRouter ejecute actualizaciones de esquema de forma determinista tanto en 
 * Supabase como en el SQLite local, manteniendo la "Triple Fuente de Verdad".
 * 
 * Se ejecuta automáticamente durante el proceso de build y en Hot Update mediante Vite.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { enableCompileCache } from 'node:module';

enableCompileCache();


const MIGRATIONS_DIR = path.resolve(process.cwd(), 'database/migrations');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/logic/db/migrations_data.ts');

export async function generateMigrations() {
  const relOutputDir = path.relative(process.cwd(), OUTPUT_FILE).replace(/\\/g, '/');

  try {
    await fs.access(MIGRATIONS_DIR);
  } catch {
    console.warn('⚠️ [Migrations Generator] Directorio database/migrations no encontrado.');
    return;
  }

  // 1. Get all SQL files (excluding .sqlite.sql which are paired as companion sql)
  const list = await fs.readdir(MIGRATIONS_DIR);

  // Verify no orphan .sqlite.sql files exist
  const sqliteFiles = list.filter(f => f.endsWith('.sqlite.sql'));
  for (const sqliteFile of sqliteFiles) {
    const baseSqlFile = sqliteFile.replace(/\.sqlite\.sql$/, '.sql');
    if (!list.includes(baseSqlFile)) {
      throw new Error(`[Migrations Generator] ERROR: Archivo SQLite huérfano detectado sin archivo base de PostgreSQL correspondiente: ${sqliteFile}. Todas las migraciones SQLite deben tener una contraparte base .sql`);
    }
  }

  const files = list
    .filter(f => f.endsWith('.sql') && !f.endsWith('.sqlite.sql') && !f.includes('baseline_schema'))
    .sort((a, b) => a.localeCompare(b));

  const migrations = await Promise.all(files.map(async (filename) => {
    const id = filename.replace(/\.sql$/, '');
    const content = await fs.readFile(path.join(MIGRATIONS_DIR, filename), 'utf-8');

    // Check for SQLite companion file
    const sqliteFilename = filename.replace(/\.sql$/, '.sqlite.sql');
    const stripInlineComment = (line: string): string => {
      let inSingle = false;
      let inDouble = false;
      for (let i = 0; i < line.length; i++) {
        const ch = line[i];
        if (ch === "'" && !inDouble) {
          if (line[i + 1] === "'") {
            i++; // skip escaped quote ''
          } else {
            inSingle = !inSingle;
          }
        } else if (ch === '"' && !inSingle) {
          if (line[i + 1] === '"') {
            i++; // skip escaped quote ""
          } else {
            inDouble = !inDouble;
          }
        } else if (ch === '-' && line[i + 1] === '-' && !inSingle && !inDouble) {
          return line.substring(0, i);
        }
      }
      return line;
    };

    const cleanContent = content
      .split('\n')
      .map(line => stripInlineComment(line).trim())
      .filter(line => line.length > 0)
      .join('\n');

    let sqliteContent: string | undefined = undefined;
    if (list.includes(sqliteFilename)) {
      const rawSqlite = await fs.readFile(path.join(MIGRATIONS_DIR, sqliteFilename), 'utf-8');
      sqliteContent = rawSqlite
        .split('\n')
        .map(line => stripInlineComment(line).trim())
        .filter(line => line.length > 0)
        .join('\n');
    }

    // Parse metadata from comments
    // Example: -- check: { "table": "profiles", "column": "role" }
    let check: Record<string, unknown> | null = null;
    const checkMatch = content.match(/--\s*check:\s*({.+})/);
    if (checkMatch && checkMatch[1]) {
      try {
        check = JSON.parse(checkMatch[1]) as Record<string, unknown>; // open-record: Generic key-value data dictionary container
      } catch (e) {
        console.error(`[Migrations Generator] Error parsing check metadata in ${filename}:`, e);
      }
    }

    return {
      id,
      sql: cleanContent,
      sqlite_sql: sqliteContent,
      check
    };
  }));

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/database/generate_migrations.ts
 * 
 * Contains all static SQL migrations for deterministic offline/in-memory schema upgrades.
 */

export const DATABASE_MIGRATIONS = ${JSON.stringify(migrations, null, 2)};
`;

  // Create directory if it doesn't exist
  const outputDir = path.dirname(OUTPUT_FILE);
  await fs.mkdir(outputDir, { recursive: true });

  try {
    if (await fs.readFile(OUTPUT_FILE, 'utf8') === output) {
      console.log(`📦 [Migrations Generator] ${relOutputDir} está actualizado (${migrations.length} migraciones).`);
      return;
    }
  } catch {
    // The manifest does not exist yet and must be created below.
  }

  {
    await using fileHandle = await fs.open(OUTPUT_FILE, 'w');
    await fileHandle.writeFile(output);
  }
  console.log(`⚡ [Migrations Generator] Generadas ${migrations.length} migraciones en ${relOutputDir}`);
}

// Support running directly
const isDirectRun = process.argv[1] && (
  process.argv[1].endsWith('generate_migrations.ts') ||
  process.argv[1].includes('generate_migrations.ts')
);

if (isDirectRun) {
  generateMigrations().catch(console.error);
}
