// fallow-ignore-file security-sink
/**
 * @file generate_migrations.js
 * @description Generador automático de manifiesto de migraciones SQL.
 * 
 * UTILIDAD: 
 * Escanea el directorio 'database/migrations/' en busca de archivos .sql y los 
 * empaqueta en un único archivo JavaScript ('src/logic/db/migrations_data.ts').
 * 
 * IMPORTANCIA: 
 * Este script es el puente entre el diseño de base de datos (SQL) y la lógica de ejecución (JS).
 * Permite que el DBRouter ejecute actualizaciones de esquema de forma determinista tanto en 
 * Supabase como en el SQLite local, manteniendo la "Triple Fuente de Verdad".
 * 
 * Se ejecuta automáticamente durante el proceso de build y en Hot Update mediante Vite.
 */

import fs from 'node:fs/promises';
import path from 'node:path';


const MIGRATIONS_DIR = path.resolve(process.cwd(), 'database/migrations');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/logic/db/migrations_data.ts');

export async function generateMigrations() {
  console.log('[Migrations Generator] Scanning directory:', MIGRATIONS_DIR);

  try {
    await fs.access(MIGRATIONS_DIR);
  } catch {
    console.warn('[Migrations Generator] Migrations directory not found.');
    return;
  }

  // 1. Get all SQL files (excluding .sqlite.sql which are paired as companion sql)
  const list = await fs.readdir(MIGRATIONS_DIR);

  // Verify no orphan .sqlite.sql files exist
  const sqliteFiles = list.filter(f => f.endsWith('.sqlite.sql'));
  for (const sqliteFile of sqliteFiles) {
    const baseSqlFile = sqliteFile.replace(/\.sqlite\.sql$/, '.sql');
    if (!list.includes(baseSqlFile)) {
      throw new Error(`[Migrations Generator] ERROR: Archivo SQLite huérfano detectado sin archivo base de PostgreSQL correspondiente: ${sqliteFile}. Todas las migraciones SQLite deben tener una contraparte base .sql`);
    }
  }

  const files = list
    .filter(f => f.endsWith('.sql') && !f.endsWith('.sqlite.sql') && !f.includes('baseline_schema'))
    .sort((a, b) => a.localeCompare(b));

  const migrations = await Promise.all(files.map(async (filename) => {
    const id = filename.replace(/\.sql$/, '');
    const content = await fs.readFile(path.join(MIGRATIONS_DIR, filename), 'utf-8');

    // Check for SQLite companion file
    const sqliteFilename = filename.replace(/\.sql$/, '.sqlite.sql');
    let sqliteSql: string | undefined = undefined;
    try {
      const sqliteContent = await fs.readFile(path.join(MIGRATIONS_DIR, sqliteFilename), 'utf-8');
      sqliteSql = sqliteContent.split('\n')
        .map(line => {
          const commentIndex = line.indexOf('--');
          if (commentIndex !== -1) {
            if (line.includes('check:')) return '';
            return line.substring(0, commentIndex);
          }
          return line;
        })
        .filter(line => line.trim().length > 0)
        .join(' ')
        .replace(/\s+/g, ' ')
        .trim();
    } catch {
      // SQLite companion does not exist, which is normal
    }

    // Parse metadata from comments
    // Example: -- check: { "table": "profiles", "column": "role" }
    let check: Record<string, unknown> | null = null;
    const checkMatch = content.match(/--\s*check:\s*({.+})/);
    if (checkMatch && checkMatch[1]) {
      try {
        check = JSON.parse(checkMatch[1]) as Record<string, unknown>;
      } catch (e) {
        console.error(`[Migrations Generator] Error parsing check metadata in ${filename}:`, e);
      }
    }

    // Prepare SQL: remove comments and normalize newlines to keep it compact
    const sqlLines = content.split('\n')
      .map(line => {
        // Strip inline comments starting with --
        const commentIndex = line.indexOf('--');
        if (commentIndex !== -1) {
          // Keep part before comment, but only if it's not the 'check:' metadata line
          if (line.includes('check:')) return '';
          return line.substring(0, commentIndex);
        }
        return line;
      })
      .filter(line => line.trim().length > 0)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();

    return {
      id,
      sql: sqlLines,
      sqlite_sql: sqliteSql,
      check
    };
  }));

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate_migrations.js
 * Last generated: ${Temporal.Now.instant().toString()}
 */

export const DATABASE_MIGRATIONS = ${JSON.stringify(migrations, null, 2)};
`;

  // Create directory if it doesn't exist
  const outputDir = path.dirname(OUTPUT_FILE);
  await fs.mkdir(outputDir, { recursive: true });

  {
    await using fileHandle = await fs.open(OUTPUT_FILE, 'w');
    await fileHandle.writeFile(output);
  }
  console.log(`[Migrations Generator] Generated ${migrations.length} migrations in ${OUTPUT_FILE}`);
}

// Support running directly
const isDirectRun = process.argv[1] && (
  process.argv[1].endsWith('generate_migrations.ts') ||
  process.argv[1].includes('generate_migrations.ts')
);

if (isDirectRun) {
  generateMigrations().catch(console.error);
}
