import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const projectRoot = 'c:/Users/Franco/Trabajos/Juegos/PokeBorrador';

const movesFile = readFileSync(join(projectRoot, 'src/data/moves.ts'), 'utf-8');
const translationsRaw = readFileSync(join(projectRoot, 'showdown/sandbox_db/data/move_translations.json'), 'utf-8');
const translations = JSON.parse(translationsRaw);

// Invert translations: Spanish -> English Key
const nameToKey: Record<string, string> = {};
for (const [key, val] of Object.entries(translations)) {
  nameToKey[(val as string).toLowerCase()] = key;
}

// Simple helper to guess snake_case from showdown lowercase ID
function toSnakeCase(id: string): string {
  const overrides: Record<string, string> = {
    solarbeam: 'solar_beam',
    quickattack: 'quick_attack',
    doubleedge: 'double_edge',
    bodyslam: 'body_slam',
    jumpkick: 'jump_kick',
    highjumpkick: 'high_jump_kick',
    flamewheel: 'flame_wheel',
    bellydrum: 'belly_drum',
    zapcannon: 'zap_cannon',
    destinybond: 'destiny_bond',
    perishsong: 'perish_song',
    icywind: 'icy_wind',
    falseswipe: 'false_swipe',
    furycutter: 'fury_cutter',
    steelwing: 'steel_wing',
    meanlook: 'mean_look',
    sleeptalk: 'sleep_talk',
    healbell: 'heal_bell',
    sacredfire: 'sacred_fire',
    dynamicpunch: 'dynamic_punch',
    dragonbreath: 'dragon_breath',
    batonpass: 'baton_pass',
    rapidspin: 'rapid_spin',
    sweetscent: 'sweet_scent',
    irontail: 'iron_tail',
    metalclaw: 'metal_claw',
    vitalthrow: 'vital_throw',
    morningsun: 'morning_sun',
    hiddenpower: 'hidden_power',
    crosschop: 'cross_chop',
    raindance: 'rain_dance',
    sunnyday: 'sunny_day',
    mirrorcoat: 'mirror_coat',
    psychup: 'psych_up',
    extremespeed: 'extreme_speed',
    ancientpower: 'ancient_power',
    shadowball: 'shadow_ball',
    futuresight: 'future_sight',
    rocksmash: 'rock_smash',
    fakeout: 'fake_out',
    heatwave: 'heat_wave',
    willowisp: 'will_o_wisp',
    focuspunch: 'focus_punch',
    smellingsalts: 'smelling_salts',
    followme: 'follow_me',
    naturepower: 'nature_power',
    helpinghand: 'helping_hand',
    roleplay: 'role_play',
    superpower: 'super_power',
    magiccoat: 'magic_coat',
    brickbreak: 'brick_break',
    knockoff: 'knock_off',
    skillswap: 'skill_swap',
    secretpower: 'secret_power',
    tailglow: 'tail_glow',
    lusterpurge: 'luster_purge',
    mistball: 'mist_ball',
    featherdance: 'feather_dance',
    teeterdance: 'teeter_dance',
    blazekick: 'blaze_kick',
    mudsport: 'mud_sport',
    iceball: 'ice_ball',
    needlearm: 'needle_arm',
    slackoff: 'slack_off',
    hypervoice: 'hyper_voice',
    poisonfang: 'poison_fang',
    crushclaw: 'crush_claw',
    blastburn: 'blast_burn',
    hydrocannon: 'hydro_cannon',
    meteormash: 'meteor_mash',
    weatherball: 'weather_ball',
    faketears: 'fake_tears',
    aircutter: 'air_cutter',
    odorsleuth: 'odor_sleuth',
    rocktomb: 'rock_tomb',
    silverwind: 'silver_wind',
    metalsound: 'metal_sound',
    grasswhistle: 'grass_whistle',
    cosmicpower: 'cosmic_power',
    waterspout: 'water_spout',
    signalbeam: 'signal_beam',
    shadowpunch: 'shadow_punch',
    skyuppercut: 'sky_uppercut',
    sandtomb: 'sand_tomb',
    sheercold: 'sheer_cold',
    muddywater: 'muddy_water',
    bulletseed: 'bullet_seed',
    aerialace: 'aerial_ace',
    iciclespear: 'icicle_spear',
    irondefense: 'iron_defense',
    dragonclaw: 'dragon_claw',
    frenzyplant: 'frenzy_plant',
    bulkup: 'bulk_up',
    mudshot: 'mud_shot',
    poisontail: 'poison_tail',
    volttackle: 'volt_tackle',
    magicalleaf: 'magical_leaf',
    watersport: 'water_sport',
    calmmind: 'calm_mind',
    leafblade: 'leaf_blade',
    dragondance: 'dragon_dance',
    rockblast: 'rock_blast',
    shockwave: 'shock_wave',
    waterpulse: 'water_pulse',
    doomdesire: 'doom_desire',
    psychoboost: 'psycho_boost',
    meteorpunch: 'meteor_punch',
    visegrip: 'vise_grip',
    // Generics
    doubleslap: 'double_slap',
    cometpunch: 'comet_punch',
    megapunch: 'mega_punch',
    payday: 'pay_day',
    firepunch: 'fire_punch',
    icepunch: 'ice_punch',
    thunderpunch: 'thunder_punch',
    razorwind: 'razor_wind',
    swordsdance: 'swords_dance',
    wingattack: 'wing_attack',
    vinewhip: 'vine_whip',
    doublekick: 'double_kick',
    megakick: 'mega_kick',
    rollingkick: 'rolling_kick',
    sandattack: 'sand_attack',
    headbutt: 'head_butt',
    hornattack: 'horn_attack',
    furyattack: 'fury_attack',
    horndrill: 'horn_drill',
    poisonsting: 'poison_sting',
    twineedle: 'twin_needle',
    pinmissile: 'pin_missile',
    tailwhip: 'tail_whip',
    bubblebeam: 'bubble_beam',
    aurorabeam: 'aurora_beam',
    hyperbeam: 'hyper_beam',
    drillpeck: 'drill_peck',
    seismictoss: 'seismic_toss',
    megadrain: 'mega_drain',
    leechseed: 'leech_seed',
    razorleaf: 'razor_leaf',
    poisonpowder: 'poison_powder',
    stunspore: 'stun_spore',
    sleeppowder: 'sleep_powder',
    petaldance: 'petal_dance',
    stringshot: 'string_shot',
    dragonrage: 'dragon_rage',
    firespin: 'fire_spin',
    thundershock: 'thunder_shock',
    thunderbolt: 'thunderbolt',
    thunderwave: 'thunder_wave',
    rockthrow: 'rock_throw',
    doubleteam: 'double_team',
    smokescreen: 'smoke_screen',
    confuseray: 'confuse_ray',
    defensecurl: 'defense_curl',
    lightscreen: 'light_screen',
    focusenergy: 'focus_energy',
    selfdestruct: 'self_destruct',
    eggbomb: 'egg_bomb',
    boneclub: 'bone_club',
    fireblast: 'fire_blast',
    spikecannon: 'spike_cannon',
    softboiled: 'soft_boiled',
    poisongas: 'poison_gas',
    leechlife: 'leech_life',
    lovelykiss: 'lovely_kiss',
    skyattack: 'sky_attack',
    dizzypunch: 'dizzy_punch',
    psywave: 'psy_wave',
    acidarmor: 'acid_armor',
    furyswipes: 'fury_swipes',
    rockslide: 'rock_slide',
    hyperfang: 'hyper_fang',
    superfang: 'super_fang',
    triplekick: 'triple_kick',
    spiderweb: 'spider_web',
    mindreader: 'mind_reader',
    cottonspore: 'cotton_spore',
    powdersnow: 'powder_snow',
    machpunch: 'mach_punch',
    scaryface: 'scary_face',
    sweetkiss: 'sweet_kiss',
    sludgebomb: 'sludge_bomb',
    mudslap: 'mud_slap',
    destinybond: 'destiny_bond',
    bonerush: 'bone_rush',
  };
  return overrides[id] || id;
}

console.log('Loaded configurations.');
