import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const projectRoot = 'c:/Users/Franco/Trabajos/Juegos/PokeBorrador';

// Load translation mapping
const translationsRaw = readFileSync(join(projectRoot, 'showdown/sandbox_db/data/move_translations.json'), 'utf-8');
const translations = JSON.parse(translationsRaw);

// Invert translations: Spanish Name -> English raw key
const nameToKey: Record<string, string> = {};
for (const [key, val] of Object.entries(translations)) {
  nameToKey[(val as string).toLowerCase()] = key;
}

// Manual corrections/additions to guarantee uniqueness
const manualTranslations: Record<string, string> = {
  'placaje': 'tackle',
  'ataque': 'tackle',
  'bofetón lodo': 'mud_slap',
  'puño lodo': 'mud_punch',
  'portazo': 'slam',
  'atizar': 'slam',
  'destructor': 'pound',
  'puñetazo': 'pound',
  'picotazo': 'peck',
  'picoteo': 'pluck',
  'golpe cabeza': 'headbutt',
  'cabezazo': 'headbutt',
  'persecución': 'pursuit',
  'seguimiento': 'pursuit',
  'rodar': 'rollout',
  'desenrrollar': 'rollout',
  'cola': 'tail_whip',
  'látigo': 'tail_whip',
  'psicocontrol': 'psicocontrol',
  'más psique': 'psych_up',
  'zap cannon': 'zap_cannon',
  'electrocañón': 'zap_cannon',
  'electrorrayo': 'electrorrayo',
  'chispa': 'spark',
  'envolver': 'wrap',
  'constricción': 'constrict',
  // Generics & specifics
  'rayo solar': 'solar_beam',
  'hoja afilada': 'razor_leaf',
  'látigo cepa': 'vine_whip',
  'polvo veneno': 'poison_powder',
  'somnífera': 'sleep_powder',
  'derribo': 'take_down',
  'dulce aroma': 'sweet_scent',
  'desarrollo': 'growth',
  'gruñido': 'growl',
  'drenadoras': 'leech_seed',
  'cuchillada': 'slash',
  'doble bofetón': 'double_slap',
  'pisotón': 'stomp',
  'doble patada': 'double_kick',
  'golpe cuerpo': 'body_slam',
  'retribución': 'return',
  'enfado': 'outrage',
  'golpe': 'thrash',
  'patada ígnea': 'blaze_kick',
  'patada salto alta': 'high_jump_kick',
  'patada salto': 'jump_kick',
  'pájaro osado': 'brave_bird',
  'engullir': 'swallow',
  'puño cometa': 'comet_punch',
  'bomba huevo': 'egg_bomb',
  'alboroto': 'uproar',
  'triturar': 'crunch',
  'paralizador': 'stun_spore',
  'disparo demora': 'string_shot',
  'bucle arena': 'sand_tomb',
  'golpes furia': 'fury_swipes',
  'colmillo veneno': 'poison_fang',
  'puño meteoro': 'meteor_mash',
  'fuego fatuo': 'will_o_wisp',
  'vozarrón': 'hyper_voice',
  'niebla': 'haze',
  'impresionar': 'astonish',
  'danza pétalo': 'petal_dance',
  'aromaterapia': 'aromatherapy',
  'megacuerno': 'megahorn',
  'fortaleza': 'harden',
  'defensa férrea': 'iron_defense',
  'agilidad': 'agility',
  'danza espada': 'swords_dance',
  'amnesia': 'amnesia',
  'rugido': 'roar',
  'canto': 'sing',
  'supersónico': 'supersonic',
  'salpicadura': 'splash',
  'furia': 'rage',
  'malicioso': 'leer',
  'chirrido': 'screech',
  'día de pago': 'pay_day',
  'finta': 'feint_attack',
  'venganza': 'bide',
  'contoneo': 'swagger',
  'tajo cruzado': 'cross_chop',
  'rastreo': 'odor_sleuth',
  'rueda fuego': 'flame_wheel',
  'tambor': 'belly_drum',
  'premonición': 'future_sight',
  'kinético': 'kinesis',
  'truco': 'trick',
  'previsión': 'foresight',
  'tiro vital': 'vital_throw',
  'velocidad extrema': 'extreme_speed',
  'fisura': 'fissure',
  'metrónomo': 'metronome',
  'sorpresa': 'fake_out',
  'tormenta arena': 'sandstorm',
  'relevo': 'baton_pass',
  'llantopanto': 'fake_tears',
  'canto mortal': 'perish_song',
  'frío polar': 'sheer_cold',
  'onda sónica': 'sonic_boom',
  'fijar blanco': 'lock_on',
  'eco metálico': 'metal_sound',
  'corte furia': 'fury_cutter',
  'falso tortazo': 'false_swipe',
  'viento hielo': 'icy_wind',
  'armadura ácida': 'acid_armor',
  'rencor': 'spite',
  'mal de ojo': 'mean_look',
  'mismodestino': 'destiny_bond',
  'puño sombra': 'shadow_punch',
  'arraigo': 'ingrain',
  'cosquillas': 'tickle',
  'puño mareo': 'dizzy_punch',
  'aguante': 'endure',
  'ciclón': 'twister',
  'danza dragón': 'dragon_dance',
  'cascada': 'waterfall',
  'giro rápido': 'rapid_spin',
  'reciclaje': 'recycle',
  'disparo lodo': 'mud_shot',
  'amortiguador': 'soft_boiled',
  'bostezo': 'yawn',
  'anulación': 'disable',
  'otra vez': 'encore',
  'foco energía': 'focus_energy',
  'refuerzo': 'helping_hand',
  'conversión 2': 'conversion2',
  'conversión': 'conversion',
  'ronquido': 'snore',
  'sonámbulo': 'sleep_talk',
  'bloqueo': 'block',
  'desenrrollar': 'rollout',
  'detección': 'detect',
  'onda ígnea': 'heat_wave',
  'ataque aéreo': 'sky_attack',
  'rapidez': 'swift',
  'camuflaje': 'camouflage',
  'masa cósmica': 'cosmic_power',
  'arañazo': 'scratch',
  'garra metal': 'metal_claw',
  'pantalla humo': 'smoke_screen',
  'furia dragón': 'dragon_rage',
  'cara susto': 'scary_face',
  'ataque ala': 'wing_attack',
  'remolino': 'whirlwind',
  'súper colmillo': 'super_fang',
  'ácido': 'acid',
  'rizo defensa': 'defense_curl',
  'gigadrenado': 'giga_drain',
  'psicorrayo': 'psybeam',
  'luz lunar': 'moonlight',
  'hipnosis': 'hypnosis',
  'ascuas': 'ember',
  'lanzallamas': 'flamethrower',
  'giro fuego': 'fire_spin',
  'llamarada': 'fire_blast',
  'burbuja': 'bubble',
  'pistola agua': 'water_gun',
  'hidrobomba': 'hydro_pump',
  'impactrueno': 'thundershock',
  'rayo': 'thunderbolt',
  'onda trueno': 'thunder_wave',
  'trueno': 'thunder',
  'lanzarrocas': 'rock_throw',
  'terremoto': 'earthquake',
  'explosión': 'explosion',
  'autodestrucción': 'self_destruct',
  'chupa-vidas': 'leech_life',
  'ala de acero': 'steel_wing',
  'silbato': 'grass_whistle',
  'estallido': 'eruption',
  'golpe roca': 'rock_smash',
  'bomba lodo': 'sludge_bomb',
  'espora': 'spore',
  'esquema': 'sketch',
  'ladrón': 'thief',
  'pico taladro': 'drill_peck',
  'cornada': 'horn_attack',
  'perforador': 'horn_drill',
  'viento cortante': 'razor_wind',
  'vuelo': 'fly',
  'sumisión': 'submission',
  'patada baja': 'low_kick',
  'contraataque': 'counter',
  'fuerza': 'strength',
  'teletransporte': 'teleport',
  'tinieblas': 'night_shade',
  'mimético': 'mimic',
  'recuperación': 'recover',
  'reducción': 'minimize',
  'pantalla de humo': 'smokescreen',
  'refugio': 'withdraw',
  'barrera': 'barrier',
  'pantalla de luz': 'light_screen',
  'lengüetazo': 'lick',
  'polución': 'smog',
  'residuos': 'sludge',
  'hueso palo': 'bone_club',
  'tenaza': 'clamp',
  'clavo cañón': 'spike_cannon',
  'restricción': 'constrict',
  'deslumbrar': 'glare',
  'comesueños': 'dream_eater',
  'gas venenoso': 'poison_gas',
  'beso amoroso': 'lovely_kiss',
  'transformación': 'transform',
  'psicoonda': 'psywave',
  'martillazo': 'crabhammer',
  'huesomerang': 'bonemerang',
  'triataque': 'tri_attack',
  'sustituto': 'substitute',
  'forcejeo': 'struggle',
  'triple patada': 'triple_kick',
  'telaraña': 'spider_web',
  'telépata': 'mind_reader',
  'pesadilla': 'nightmare',
  'azote': 'flail',
  'aerochorro': 'aeroblast',
  'esporagodón': 'cotton_spore',
  'inversión': 'reversal',
  'nieve polvo': 'powder_snow',
  'protección': 'protect',
  'ultrapuño': 'mach_punch',
  'beso dulce': 'sweet_kiss',
  'pulpocañón': 'octazooka',
  'púas': 'spikes',
  'profecía': 'foresight',
  'ataque óseo': 'bone_rush',
  'encanto': 'charm',
  'batido': 'milk_drink',
  'campana cura': 'heal_bell',
  'presente': 'present',
  'frustración': 'frustration',
  'divide dolor': 'pain_split',
  'fuego sagrado': 'sacred_fire',
  'magnitud': 'magnitude',
  'puño dinámico': 'dynamic_punch',
  'dragoaliento': 'dragon_breath',
  'cola férrea': 'iron_tail',
  'sol matinal': 'morning_sun',
  'poder oculto': 'hidden_power',
  'danza lluvia': 'rain_dance',
  'día soleado': 'sunny_day',
  'manto espejo': 'mirror_coat',
  'poder pasado': 'ancient_power',
  'bola sombra': 'shadow_ball',
  'torbellino': 'whirlpool',
  'paliza': 'beat_up',
  'reserva': 'stockpile',
  'escupir': 'spit_up',
  'tragar': 'swallow',
  'tormento': 'torment',
  'camelo': 'flatter',
  'legado': 'memento',
  'imagen': 'facade',
  'puño certero': 'focus_punch',
  'estímulo': 'smelling_salts',
  'señuelo': 'follow_me',
  'adaptación': 'nature_power',
  'mofa': 'taunt',
  'imitación': 'role_play',
  'deseo': 'wish',
  'ayuda': 'assist',
  'fuerza bruta': 'superpower',
  'capa mágica': 'magic_coat',
  'desarme': 'knock_off',
  'alivio': 'refresh',
  'rabia': 'grudge',
  'robo': 'snatch',
  'daño secreto': 'secret_power',
  'buceo': 'dive',
  'empujón': 'arm_thrust',
  'ráfaga': 'tail_glow',
  'resplandor': 'luster_purge',
  'bola neblina': 'mist_ball',
  'danza pluma': 'feather_dance',
  'danza caos': 'teeter_dance',
  'chapoteo lodo': 'mud_sport',
  'bola hielo': 'ice_ball',
  'brazo pincho': 'needle_arm',
  'relajo': 'slack_off',
  'garra brutal': 'crush_claw',
  'anillo ígneo': 'blast_burn',
  'hidrocañón': 'hydro_cannon',
  'llanto falso': 'fake_tears',
  'aire afilado': 'air_cutter',
  'sofoco': 'overheat',
  'tumba rocas': 'rock_tomb',
  'viento plata': 'silver_wind',
  'salpicar': 'water_spout',
  'doble rayo': 'signal_beam',
  'paranormal': 'extrasensory',
  'gancho alto': 'sky_uppercut',
  'agua lodosa': 'muddy_water',
  'semilladora': 'bullet_seed',
  'golpe aéreo': 'aerial_ace',
  'carámbano': 'icicle_spear',
  'aullido': 'howl',
  'planta feroz': 'frenzy_plant',
  'corpulencia': 'bulk_up',
  'bote': 'bounce',
  'cola veneno': 'poison_tail',
  'antojo': 'covet',
  'placaje eléc': 'volt_tackle',
  'hoja mágica': 'magical_leaf',
  'hidrochorro': 'water_sport',
  'paz mental': 'calm_mind',
  'hoja aguda': 'leaf_blade',
  'pedrada': 'rock_blast',
  'onda voltio': 'shock_wave',
  'hidropulso': 'water_pulse',
  'deseo oculto': 'doom_desire',
  'psicoataque': 'psycho_boost',
  'vise grip': 'vise_grip',
  'golpe karatazo': 'karate_chop',
  'puñetazo': 'pound'
};

function getSnakeId(name: string): string {
  const normalizedName = name.trim().toLowerCase();
  if (manualTranslations[normalizedName]) {
    return manualTranslations[normalizedName];
  }
  const rawKey = nameToKey[normalizedName];
  if (rawKey) {
    const snakeOverrides: Record<string, string> = {
      solarbeam: 'solar_beam',
      quickattack: 'quick_attack',
      doubleedge: 'double_edge',
      bodyslam: 'body_slam',
      jumpkick: 'jump_kick',
      highjumpkick: 'high_jump_kick',
      flamewheel: 'flame_wheel',
      bellydrum: 'belly_drum',
      zapcannon: 'zap_cannon',
      destinybond: 'destiny_bond',
      perishsong: 'perish_song',
      icywind: 'icy_wind',
      falseswipe: 'false_swipe',
      furycutter: 'fury_cutter',
      steelwing: 'steel_wing',
      meanlook: 'mean_look',
      sleeptalk: 'sleep_talk',
      healbell: 'heal_bell',
      sacredfire: 'sacred_fire',
      dynamicpunch: 'dynamic_punch',
      dragonbreath: 'dragon_breath',
      batonpass: 'baton_pass',
      rapidspin: 'rapid_spin',
      sweetscent: 'sweet_scent',
      irontail: 'iron_tail',
      metalclaw: 'metal_claw',
      vitalthrow: 'vital_throw',
      morningsun: 'morning_sun',
      hiddenpower: 'hidden_power',
      crosschop: 'cross_chop',
      raindance: 'rain_dance',
      sunnyday: 'sunny_day',
      mirrorcoat: 'mirror_coat',
      psychup: 'psych_up',
      extremespeed: 'extreme_speed',
      ancientpower: 'ancient_power',
      shadowball: 'shadow_ball',
      futuresight: 'future_sight',
      rocksmash: 'rock_smash',
      fakeout: 'fake_out',
      heatwave: 'heat_wave',
      willowisp: 'will_o_wisp',
      focuspunch: 'focus_punch',
      smellingsalts: 'smelling_salts',
      followme: 'follow_me',
      naturepower: 'nature_power',
      helpinghand: 'helping_hand',
      roleplay: 'role_play',
      superpower: 'super_power',
      magiccoat: 'magic_coat',
      brickbreak: 'brick_break',
      knockoff: 'knock_off',
      skillswap: 'skill_swap',
      secretpower: 'secret_power',
      tailglow: 'tail_glow',
      lusterpurge: 'luster_purge',
      mistball: 'mist_ball',
      featherdance: 'feather_dance',
      teeterdance: 'teeter_dance',
      blazekick: 'blaze_kick',
      mudsport: 'mud_sport',
      iceball: 'ice_ball',
      needlearm: 'needle_arm',
      slackoff: 'slack_off',
      hypervoice: 'hyper_voice',
      poisonfang: 'poison_fang',
      crushclaw: 'crush_claw',
      blastburn: 'blast_burn',
      hydrocannon: 'hydro_cannon',
      meteormash: 'meteor_mash',
      weatherball: 'weather_ball',
      faketears: 'fake_tears',
      aircutter: 'air_cutter',
      odorsleuth: 'odor_sleuth',
      rocktomb: 'rock_tomb',
      silverwind: 'silver_wind',
      metalsound: 'metal_sound',
      grasswhistle: 'grass_whistle',
      cosmicpower: 'cosmic_power',
      waterspout: 'water_spout',
      signalbeam: 'signal_beam',
      shadowpunch: 'shadow_punch',
      skyuppercut: 'sky_uppercut',
      sandtomb: 'sand_tomb',
      sheercold: 'sheer_cold',
      muddywater: 'muddy_water',
      bulletseed: 'bullet_seed',
      aerialace: 'aerial_ace',
      iciclespear: 'icicle_spear',
      irondefense: 'iron_defense',
      dragonclaw: 'dragon_claw',
      frenzyplant: 'frenzy_plant',
      bulkup: 'bulk_up',
      mudshot: 'mud_shot',
      poisontail: 'poison_tail',
      volttackle: 'volt_tackle',
      magicalleaf: 'magical_leaf',
      watersport: 'water_sport',
      calmmind: 'calm_mind',
      leafblade: 'leaf_blade',
      dragondance: 'dragon_dance',
      rockblast: 'rock_blast',
      shockwave: 'shock_wave',
      waterpulse: 'water_pulse',
      doomdesire: 'doom_desire',
      psychoboost: 'psycho_boost',
      meteorpunch: 'meteor_punch',
      visegrip: 'vise_grip',
    };
    return snakeOverrides[rawKey] || rawKey;
  }
  return normalizedName
    .replace(/[áäàâ]/g, 'a')
    .replace(/[éëèê]/g, 'e')
    .replace(/[íïìî]/g, 'i')
    .replace(/[óöòô]/g, 'o')
    .replace(/[úüùû]/g, 'u')
    .replace(/[ñ]/g, 'n')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

// Read backup/original source of moves
console.log('Restoring and parsing moves with distinct keys...');
const backupMovesPath = join(projectRoot, 'backup_legacy_code/js/02_pokemon_data.js');
const backupContent = readFileSync(backupMovesPath, 'utf-8');

// Parse move data object from backup file (lines starting with 'Rayo Solar': etc. in 02_pokemon_data.js)
const moveDefinitionRegex = /^\s*'([^']+)':\s*({[^}]+}),?/gm;
const moves: Record<string, string> = {};

let match;
while ((match = moveDefinitionRegex.exec(backupContent)) !== null) {
  const spanishName = match[1];
  const body = match[2];
  const snakeId = getSnakeId(spanishName);
  moves[snakeId] = `  '${snakeId}': { id: '${snakeId}', name: '${spanishName}', ${body.slice(1, -1)} },`;
}

// Re-generate moves.ts content dynamically to ensure uniqueness of keys
let movesTsContent = 'export const MOVE_DATA: Record<string, any> = {\n';
for (const entry of Object.values(moves)) {
  movesTsContent += entry + '\n';
}
movesTsContent += '};\n';

const movesTsPath = join(projectRoot, 'src/data/moves.ts');
writeFileSync(movesTsPath, movesTsContent, 'utf-8');
console.log('src/data/moves.ts successfully migrated without duplicate keys!');

// Run learnsets update
console.log('Migrating src/data/pokemonDB.ts learnsets...');
const pokemonDBPath = join(projectRoot, 'src/data/pokemonDB.ts');
const originalPokemonDB = readFileSync(join(projectRoot, 'docs/archives/_js_backup/src/data/pokemonDB.js'), 'utf-8');

const learnsetEntryRegex = /\{\s*lv:\s*(\d+),\s*name:\s*'([^']*)',\s*pp:\s*(\d+)\s*\}/g;
const migratedPokemonDB = originalPokemonDB.replace(learnsetEntryRegex, (fullMatch, lv, name, pp) => {
  const snakeId = getSnakeId(name);
  return `{ lv: ${lv}, id: '${snakeId}', name: '${name}', pp: ${pp} }`;
});

// Since the current pokemonDB.ts in src might have other Vue imports or types, let's just do a string replacement on the active file
let activeDBContent = readFileSync(pokemonDBPath, 'utf-8');
activeDBContent = activeDBContent.replace(learnsetEntryRegex, (fullMatch, lv, name, pp) => {
  const snakeId = getSnakeId(name);
  return `{ lv: ${lv}, id: '${snakeId}', name: '${name}', pp: ${pp} }`;
});
writeFileSync(pokemonDBPath, activeDBContent, 'utf-8');
console.log('src/data/pokemonDB.ts successfully migrated!');
