/**
 * AUTO-GENERATED OFFICIAL SERVERS CONFIGURATION
 * Generated by scripts/configure_official_servers.ts
 * Last configured: 2026-05-17T05:04:52.346969971Z
 * 
 * Lista de servidores registrados para la GUI de Login.
 * Creado automáticamente a partir del archivo .env maestro.
 */

export interface OfficialServer {
  id: string;
  name: string;
  region: string;
  url: string;
  anonKey: string;
  isDefault?: boolean;
}

export const OFFICIAL_SERVERS: OfficialServer[] = [
  {
    id: 'official-prod',
    name: 'Poké Vicio Oficial',
    region: 'Global',
    url: 'https://wakrkvizmoqdlrtnxcth.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indha3Jrdml6bW9xZGxydG54Y3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMDA3MjYsImV4cCI6MjA4ODg3NjcyNn0.l_NYYNPDFOAr5CRqbuVf3jLv_TRnOw6shw9j9GzhQsA',
    isDefault: true
  },
  {
    id: 'nas-franco',
    name: 'Franco NAS (Docker)',
    region: 'Desarrollo',
    url: 'http://192.168.88.200:8000',
    anonKey: 'eyJhbGciOiAiSFMyNTYiLCAidHlwIjogIkpXVCJ9.eyJyb2xlIjogImFub24iLCAiaXNzIjogInN1cGFiYXNlIiwgImlhdCI6IDE3Nzg5NTUwNDgsICJleHAiOiAxOTM2NjM1MDQ4fQ.fnBRd9GTH0Ab_ru1AgigCAcgb9WhttqwGXB_EiyUEGA'
  }
];

export const DEFAULT_SERVER = (OFFICIAL_SERVERS.find(s => s.isDefault) || OFFICIAL_SERVERS[0]) as OfficialServer;
